### PR TITLE
Update codepwners of /cmd/cli/plugin/package/kctrl

### PR DESCRIPTION
**Pull request by praveenrewar**
### What this PR does / why we need it
Update codeowners of `/cmd/cli/plugin/package/kctrl`.
Use a smaller group to avoid review notifications being sent to a larger group of people.

### CODE REVIEW

**Review by vijaykatam — COMMENTED** [review]
+1 on change. Clean up PR template and this should be ready to merge.

**Comment by praveenrewar** [comment]
> Clean up PR template and this should be ready to merge.

Done.

**Comment by vijaykatam** [comment]
> > Clean up PR template and this should be ready to merge.
> 
> Done.

The PR template still has sections that are empty. Could you remove the ones that are not relevant? (for example fixes and testing done)

**Comment by praveenrewar** [comment]
> The PR template still has sections that are empty. Could you remove the ones that are not relevant?

Ah, I see what you meant by cleanup. Done. Thanks :)

**Review by vijaykatam — APPROVED** [review]

**Pull request merged**
