### PR TITLE
Adding cert-manager v1.9.1 maifest in providers

### LINKED ISSUE #3790: Add support for cert-manager v1.9.1 manifest in providers
**Describe the feature request**
In order to support cert-manager v1.9.1, provider bundle should include the cert-manager v1.9.1 manifests.

**Describe alternative(s) you've considered**
NA

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Additional context**
-

### PR DESCRIPTION
**Pull request by sathyanarays**
Signed-off-by: Sathyanarayanan Saravanamuthu <sathyanarays@.vmware.com>

### What this PR does / why we need it
The provider bundle should include cert-manager v1.9.1.

### Which issue(s) this PR fixes

Fixes #3790

### Describe testing done for PR
The PR pipelines create management clusters using `mc` plugins which use the latest manifests

### Release note

```release-note
Added cert-manager v1.9.1 manifests to the providers.
```

### CODE REVIEW

**Comment by sathyanarays** [comment]
> @sathyanarays can you add testing that has been done in the pr description?

@yharish991 , there is not testing done so far. Can you please provide pointers on what all testing need to be done?

**Comment by sathyanarays** [comment]
> > @sathyanarays can you add testing that has been done in the pr description?
> 
> @yharish991 , there is not testing done so far. Can you please provide pointers on what all testing need to be done?

Tested by the PR pipelines

**Review by yharish991 — APPROVED** [review]
Looks good to me in general!! Can you squash the commits into meaningful commits when you are about to merge? thanks..

**Review by vuil — APPROVED** [review]
lgtm

**Review by tenczar — APPROVED** [review]
LGTM, agree with the comment about squashing.

**Pull request merged**
