### PR TITLE
Enable tkg-windows template automatically CBT Windows

### PR DESCRIPTION
**Pull request by knabben**
### What this PR does / why we need it
When using IS_WINDOWS_WORKLOAD_CLUSTER the tkg-windows package must be installed automatically from the CBT.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-vc7
Commit: 9e664c3

Build failed! Build no: 3344

**Comment by randomvariable** [comment]
I don't think this code path is exercised by install-vc7 and is otherwise safe.

**Comment by randomvariable** [comment]
Approving for merge after main / build succeeds.

**Comment by randomvariable** [comment]
Looks fine. Queued after #3862 and #3846. You may need to rebase afterwards.

**Review by randomvariable — APPROVED** [review]

**Comment by randomvariable** [comment]
Merging, as there are no other conflicting PRs.

**Pull request merged**
