### PR TITLE
Bump Cluster API to v1.2.6 and CAPA to v2.0.1

### PR DESCRIPTION
**Pull request by ykakarap**
### What this PR does / why we need it

This PR bumps the ClusterAPI version to v1.2.6 and CAPA to v2.0.1

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.7.0-zshippable/433586624639539996/tkg-compatibility:v12

**Comment by jeffwubj** [comment]
CAPA pipeline failed at
```
 msg: "failed to get provider components for the \"cluster-api:v1.2.4\" provider: failed to read \"core-components.yaml\" from provider's repository \"cluster-api\": failed to read file \"/home/runner/.config/tanzu/tkg/providers/cluster-api/v1.2.4/core-components.yaml\" from local release v1.2.4: stat /home/runner/.config/tanzu/tkg/providers/cluster-api/v1.2.4/core-components.yaml: no such file or directory, this can be possible because of the outbound connectivity issue. Please check deployed nodes for outbound connectivity.",
``` 
assume config.yaml is still referenced to v1.2.4 instead of bumped v1.2.5. this file should lives in providerTemplateImage which comes from downstream mirror repo, so probably need a downstream BoM to make upstream pipeline happy.

**Comment by sonasingh46** [comment]
@ykakarap -- You can remove the cherry picked commit of mine for aad-pod-identity tolerations. 
I have moved it to a different PR ( after our discussion )
https://github.com/vmware-tanzu/tanzu-framework/pull/3947

**Comment by srm09** [comment]
//usebom:sandbox/v1.7.0-zshippable/435711528973376403/tkg-compatibility:v12

**Comment by alfredthenarwhal** [comment]
> @sbueringer: /retest
Commit: c554cce

Tests failed! Build no: 3333

**Review by randomvariable — APPROVED** [review]

**Comment by randomvariable** [comment]
Included #4006 which is the other PR that was touching a lot of the go.mod files to avoid repeat rebases.

**Comment by alfredthenarwhal** [comment]
> @randomvariable: /retest
Commit: 2767117

Build failed! Build no: 3353

**Comment by wjun** [comment]
@srm09 Would you change the cobra version back to the original version as discussed?

**Review by imikushin — APPROVED** [review]
LGTM. Thanks!

**Comment by randomvariable** [comment]
I've removed "/ok-to-merge" since @wjun's question has gone unanswered.

**Comment by srm09** [comment]
> Would you change the cobra version back to the original version as discussed?

@wjun Pinned the cobra version back to 1.5.0 to make sure that the kctrl tests pass.

**Review by wjun — APPROVED** [review]

**Pull request merged**
