### PR TITLE
[release-0.28] cherry-pick 4361: Fix getting AWSCluster through Cluster name

### PR DESCRIPTION
**Pull request by 12345lcr**
Cherry-pick of https://github.com/vmware-tanzu/tanzu-framework/pull/4361 into release-0.28 branch

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @12345lcr:  /test upgrade-aws
Commit: ca6f26e

Tests failed! Build no: 4098

**Review by DanielXiao — APPROVED** [review]

**Pull request merged**
