### PR TITLE
Load proxy CA to TKG Management cluster and Workload cluster's node's CA trust store

### PR DESCRIPTION
**Pull request by lubronzhan**
### What this PR does / why we need it
Currently, when using proxy with ssl termination, deploying workload that image is in docker/gcr, the workload would fail.
This is because containerd's config has the proxy ca cert mapped to projects.registry.vmware.com. It can't validate other registry with that cert.

This PR make the node VM (Management cluster and Workload cluster, not kind) trust the CA cert of proxy, so that when pulling images, containerd will trust the CA of proxy.
Kind case is kind of tricky since it can't be covered by a simple overlay and customer's are supposed to deploy workload with image from third party registry.
### Which issue(s) this PR fixes

Fixes #https://github.com/vmware-tanzu/tanzu-framework/issues/1966

### Release note

```release-note
Load proxy CA passed in `TKG_PROXY_CA_CERT ` to TKG cluster's CA trust store
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by anujc25** [comment]
```
+      - which rehash_ca_certificates.sh 2>/dev/null || rehash_ca_certificates.sh
+      - which update-ca-certificates 2>/dev/null || (mv /etc/ssl/certs/tkg-custom-ca.pem /usr/local/share/ca-certificates/tkg-custom-ca.crt && update-ca-certificates)
+      - which update-ca-trust 2>/dev/null || (update-ca-trust force-enable && mv /etc/ssl/certs/tkg-custom-ca.pem /etc/pki/ca-trust/source/anchors/tkg-custom-ca.crt && update-ca-trust extract)
+      - systemctl restart containerd
       - echo '[plugins."io.containerd.grpc.v1.cri".registry.configs."projects-stg.registry.vmware.com".tls]' >> /etc/containerd/config.toml
       - echo '  ca_file = "/etc/containerd/projects-stg.registry.vmware.com.crt"' >> /etc/containerd/config.toml
       - systemctl restart containerd
```

Just wanted to make sure that restarting `containerd` twice like this will not cause any issue or delays, right?

**Comment by lubronzhan** [comment]
No it won't

**Comment by lubronzhan** [comment]
> > https://storage.googleapis.com/tkg-clustergen/1967/20220331051351/clustergen.diff.txt
> 
> ```
> +      - which rehash_ca_certificates.sh 2>/dev/null || rehash_ca_certificates.sh
> +      - which update-ca-certificates 2>/dev/null || (mv /etc/ssl/certs/tkg-custom-ca.pem /usr/local/share/ca-certificates/tkg-custom-ca.crt && update-ca-certificates)
> +      - which update-ca-trust 2>/dev/null || (update-ca-trust force-enable && mv /etc/ssl/certs/tkg-custom-ca.pem /etc/pki/ca-trust/source/anchors/tkg-custom-ca.crt && update-ca-trust extract)
> +      - systemctl restart containerd
>        - echo '[plugins."io.containerd.grpc.v1.cri".registry.configs."projects-stg.registry.vmware.com".tls]' >> /etc/containerd/config.toml
>        - echo '  ca_file = "/etc/containerd/projects-stg.registry.vmware.com.crt"' >> /etc/containerd/config.toml
>        - systemctl restart containerd
> ```
> 
> Just wanted to make sure that restarting `containerd` twice like this will not cause any issue or delays, right?

It will cause delay, but only few seconds. No other issues though

**Review by anujc25 — APPROVED** [review]
Looks good

**Comment by lubronzhan** [comment]
The build failed but it got triggered again, now build succeeded. And it's triggering to create a cluster as well

**Comment by lubronzhan** [comment]
Saw this error in the kapp pod 
```
$ kubectl logs kapp-controller-84bf56dcdc-qc7fs -n tkg-system
{"level":"info","ts":1649112041.749392,"logger":"kc","msg":"Waited for 1.039323807s due to client-side throttling, not priority and fairness, request: GET:https://100.64.0.1:443/apis/acme.cert-manager.io/v1?timeout=32s\n"}
{"level":"info","ts":1649112046.906747,"logger":"kc.controller","msg":"setting up controller"}
{"level":"info","ts":1649112046.917974,"logger":"kc.controller","msg":"setting up metrics"}
{"level":"error","ts":1649112047.3326623,"logger":"kc.main","msg":"Exited run with error","error":"Building API server: error creating self-signed certificates: mkdir /home/kapp-controller: permission denied","stacktrace":"runtime.main\n\truntime/proc.go:255"}
{"level":"error","ts":1649112047.3383598,"logger":"kc.init","msg":"Could not start controller","error":"exit status 1","stacktrace":"main.main\n\t./main.go:53\nruntime.main\n\truntime/proc.go:255"}
```
It should be unrelated to this change. Not happening on 1.5 branch. Did we bump the kapp?

**Comment by lubronzhan** [comment]
The kapp version for 1.5.3:
```
    Image:         projects-stg.registry.vmware.com/tkg/kapp-controller@sha256:d11c017b151bb08c8a9699715495589ee64158ff0d79dba08a06a121de732a75
    Image ID:      projects-stg.registry.vmware.com/tkg/kapp-controller@sha256:d11c017b151bb08c8a9699715495589ee64158ff0d79dba08a06a121de732a75
```
The kapp version for 1.6
```
    Image:         projects-stg.registry.vmware.com/tkg/kapp-controller:v0.34.0_vmware.1
    Image ID:      projects-stg.registry.vmware.com/tkg/kapp-controller@sha256:f1fa5d6ec3a3328f24ad7205d1a6756a022e3c28c129079ec8c012ab6017f286
```

**Pull request merged**
