### PR TITLE
VSphere Cluster CC/Template: Use local_hostname instead of FQDN for node name

### PR DESCRIPTION
**Pull request by randomvariable**
K8s resources are limited to 63 characters, so to ensure nodes can
join, they should not include the complete FQDN and instead be
limited only to the local hostname.

Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note
In all vSphere clusterclasses, we now use local_hostname instead of FQDN for node registration to avoid hitting 63 character limit.
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @randomvariable:  /test install-vc7
Commit: 66d656b

Tests failed! Build no: 3531

**Comment by alfredthenarwhal** [comment]
> @randomvariable:  /test install-vc7
Commit: 66d656b

Tests failed! Build no: 3535

**Comment by jayunit100** [comment]
looking into these now

**Comment by jayunit100** [comment]
looks like several unit tests failing.  Im looking at them now.

**Comment by jayunit100** [comment]
digging into test failures now.....

**Review by lubronzhan — APPROVED** [review]
lgtm

**Pull request merged**
