### PR TITLE
Change the certificate struct for clusterclass, combining all certs into one encoding

### PR DESCRIPTION
**Pull request by lubronzhan**
…er annotation

### What this PR does / why we need it
Change the format of trust.cert to align with different products
```
name: trust
  value:
     additionalTrustedCAs:
         - name: CompanyInternalCA-1
           data: aGVsbG8=
        - name: CompanyInternalCA-2
           data: bHWtcH9=

```

Also when reading the cert and put into annotation, combine all the certs in one encoding
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-v7
Commit: d6e6f57

Tests failed! Build no: 3326

**Comment by randomvariable** [comment]
don't understand the downstream test result at all. looks like it failed to trigger.

**Review by tenczar — APPROVED** [review]
LGTM. This matches with the tkgs clusterclass right?

**Comment by lubronzhan** [comment]
> LGTM. This matches with the tkgs clusterclass right?

This doesn't matches TKGs either, Ken Pan has a story to catch up with this as well.
I just set up a standard,

**Comment by tenczar** [comment]
> > LGTM. This matches with the tkgs clusterclass right?
> 
> This doesn't matches TKGs either, Ken Pan has a story to catch up with this as well. I just set up a standard,

Cool. I just want to make sure we are trying to keep tkgs and tkgm in sync as much as possible.

**Pull request merged**
