### PR TITLE
remove ipv6 workaround from post kubeadm

### PR DESCRIPTION
**Pull request by adobley**
### What this PR does / why we need it
all current versions of tanzu are using a new-enough version of containerd (v1.5.0 or greater) that we can remove this workaround

the issue this addressed was fixed in
https://github.com/containerd/containerd/pull/5145

### Describe testing done for PR
Created a cluster to verify it comes up without this workaround

### Release note

```release-note
N/A
```

### CODE REVIEW

**Review by christianang — APPROVED** [review]

**Comment by imikushin** [comment]
**question:** Does this only apply to vsphere?

**Comment by christianang** [comment]
Yes, we only support ipv6 on vsphere at the moment.

**Review by tenczar — APPROVED** [review]
This will need to be rebased because of the providers bump, but looks good so far. Do we want to remove this hack from the legacy overlays as well?

**Review by lubronzhan — APPROVED** [review]
LGTM

**Review by DanielXiao — COMMENTED** [review]
Can you rebase this PR? There is a folder name change in https://github.com/vmware-tanzu/tanzu-framework/pull/3772

**Pull request merged**
