### PR TITLE
Adds missing github actions for setting Node version in Release and Release Staging

### PR DESCRIPTION
**Pull request by miclettej**
Adds missing github actions for setting Node version in Release and Release Staging

Seeing consistent failures in Release Staging because of Node version mismatch, causing zz generated bindata verification to fail

### Describe testing done for PR

Test running CI jobs by temporarily adding them to run on pull request. Will revert before merging to main.

Screen Shot 2021-12-02 at 12 37 53 PM

Screen Shot 2021-12-02 at 12 37 42 PM

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by rajathagasthya — APPROVED** [review]
Thanks for the quick fix!

**Review by saimanoj01 — APPROVED** [review]
LGTM

**Comment by miclettej** [comment]
Adding @anujc25 for a code owner +1

**Review by navidshaikh — APPROVED** [review]

**Review by vuil — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
