### PR TITLE
Cherry-Pick #4291 - Ensure legacy cluster upgrade does not overwrite kube-apiserver admission-control-config-file flag

### PR DESCRIPTION
**Pull request by chrischdi**
### What this PR does / why we need it

Fixes the legacy cluster upgrade to not overwrite an previously existing kube-apiserver flag `admission-control-config-file` in KCP.

* cherry-picks #4291 

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by navidshaikh** [comment]
hold for #4291 to be merged first

**Comment by chrischdi** [comment]
- https://github.com/vmware-tanzu/tanzu-framework/pull/4291

Got merged.

Rebased this cherry-pick PR.

**Review by wjun — APPROVED** [review]

**Pull request merged**
