### PR TITLE
make 'go mod vendor' idempotent, add required providers.zip

### PR DESCRIPTION
**Pull request by navidshaikh**
### What this PR does / why we need it
- Adds `tkg/tkgctl/client/manifest/providers.zip` file required for `go mod vendor` to pass
- How? (all *.zip are ignored in .gitignore file)
      - update .gitignore to allow adding `tkg/tkgctl/client/manifest/providers.zip` (explicitly) while ignoring all other `providers.zip`
      - add `tkg/tkgctl/client/manifest/providers.zip` file, commit it
      - revert `.gitignore` changes in step 1 and ignore all subsequent changes to providers.zip files
 - Verify `go mod vendor` check in build step of CI passes 
    
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by DanielXiao** [comment]
Why do you add a providers.zip to source code? If this is just for CI, you can run a command to make the zip bundle.

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7
Commit: 186ff21

Tests passed! Build no: 3874

**Comment by vuil** [comment]
nit: If the goal is just to make 'go mod vendor' complete cleaning. An empty file for providers.zip would do as well.

**Comment by navidshaikh** [comment]
thanks for review!, handling the fix elsewhere in the pipeline, this change is not needed anymore.

**Pull request closed without merging**
