### PR TITLE
Add ipv6 localhost to /etc/hosts on ipv6 nodes

### PR DESCRIPTION
**Pull request by adobley**
### What this PR does / why we need it
We removed a workaround for containerd in https://github.com/vmware-tanzu/tanzu-framework/pull/3765

[Containerd expects localhost to point to 127.0.0.1 and to ::1 for port forwarding support.](https://github.com/containerd/containerd/blob/main/pkg/cri/server/sandbox_portforward_linux.go#L64-L65) This change will add `::1 localhost` to the hosts file when the node is IPv6. 

### Describe testing done for PR

We created a cluster using clusterclass on vSphere and saw that our change was applied correctly.

We are running networking sonobuoy tests on that cluster now.

### Release note

```release-note
On IPv6 nodes localhost will resolve to ::1
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @adobley:  /test install-vc7
Commit: 289fa12

Build failed! Build no: 3177

**Comment by alfredthenarwhal** [comment]
> @adobley:  /test install-vc7
Commit: 187d47a

Build failed! Build no: 3184

**Comment by vuil** [comment]
looks like the clustergen tests for vsphere configs are broken due to d124a45a8e4f5682bcdebb1a74ada47920c2cd0c 
cc @hongtaiwang 
Would have been nice to also see the clustergen diffs due to this change. 

Changes lgtm.

**Review by vuil — APPROVED** [review]

**Review by lubronzhan — APPROVED** [review]

**Pull request merged**
