### PR TITLE
Set clusterkind explicitly from constant instead of retrieving from o…

### PR DESCRIPTION
**Pull request by lubronzhan**
…bject that's cast from an interface

Right now the enqueue doesn't take effect since the kind is missing from the casted object, thus if cluster has change, correponding addon config is still not enqueued, thus cluster creation still takes long time
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 278f33d

Tests failed! Build no: 3414

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 13f6791

Build failed! Build no: 3421

**Review by wjun — APPROVED** [review]
LGTM

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 1ea2aa4

Tests failed! Build no: 3439

**Pull request merged**
