### PR TITLE
Add nodeselector, deployment and daemonset options to kapp-controller data-values

### LINKED ISSUE #2758: Installation of kapp-controller on bootstrap cluster fails
**Bug description**
Installation of kapp-controller on bootstrap cluster fails due to the below error:

```
Error: unable to set up management cluster: unable to install kapp-controller to bootstrap cluster: error while running ytt: 
- struct has no .nodeSelector field or method
    in kapp_controller_values
      kapp-controller.yaml:13 | nodeSelector: #@ data.values.nodeSelector
    in <toplevel>
      kapp-controller.yaml:23 | --- #@ template.replace(kapp_controller_lib.with_data_values(kapp_controller_values()).eval())
Error: exit status 1
```

This is because recently nodeSelector, deployment and daemonset options were added to kapp-controller package but the kapp-controller-data-values. is not updated in tanzu-framework and that causes rendering issues.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Kapp-controller to be successfully installed in bootstrap cluster

**Steps to reproduce the bug**
tanzu management-cluster create

**Version** (include the SHA if the version is not obvious)
latest main

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by shyaamsn**
Signed-off-by: Shyaam Nagarajan <nagarajans@vmware.com>

### What this PR does / why we need it
Recently to kapp-controller package a change was introduced to add node-selector, deployment and daemonset options. But these options were not added kapp-controller data-values in tanzu-framework. This causes installation issues for kapp-controller
 
### Which issue(s) this PR fixes
Fixes #2758

### Describe testing done for PR
ytt rendered the kapp-controller-data-values file with kapp-controller package

### Release note
```release-note
package-based-lcm: Add nodeselector, deployment and daemonset options to kapp-controller data-values to fix kapp-controller ytt template not being rendered and causing installation failure
```

### PR Checklist
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by shivaani0505 — APPROVED** [review]
LGTM

**Review by vuil — APPROVED** [review]
lgtm, but hold until downstream test

**Comment by alfredthenarwhal** [comment]
Tests failed! Build no: 2260

**Review by vijaykatam — APPROVED** [review]

**Comment by vuil** [comment]
CAPA test passing is reasonable signal that this unblocks the CI. Merging.

**Pull request merged**
