### PR TITLE
Remove kube-rbac-proxy in akoo manifest in Bootstrap Cluster

### PR DESCRIPTION
**Pull request by lubronzhan**
### What this PR does / why we need it
We still reference kube-rbac-proxy in akoo manifest in Bootstrap Cluster, we already removed it from packages itself

### Which issue(s) this PR fixes

Fixes #https://github.com/vmware-tanzu/tanzu-framework/issues/3710

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2965

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2967

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2982

**Comment by randomvariable** [comment]
Rebase, and it should be fine.

**Review by randomvariable — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 3002

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 3012

**Review by XudongLiuHarold — APPROVED** [review]
LGTM, thanks @lubronzhan !

**Comment by XudongLiuHarold** [comment]
Downstream test passed, merge

**Pull request merged**
