### PR TITLE
cmd/cli/plugin/pinniped-auth: Upgrade Pinniped to 0.12.1

### PR DESCRIPTION
**Pull request by sabbey37**
Co-authored-by: Andrew Keesler <akeesler@vmware.com>
Co-authored-by: Sarah Abbey <sabbey@vmware.com>

### What this PR does / why we need it
Add Pinniped 0.12.1 package to bring in bug fix release for an incompatibility between the Pinniped CLI and Chrome v98+ that causes browser-based logins to fail.

### Which issue(s) this PR fixes
None

### Describe testing done for PR
- Built CLI locally, verified Pinniped binary version, ensured I could login.
- Built post-deploy job and patched it in TKG on vSphere instance, verified I could login.
- Ran automated LDAP and OIDC tests agains vSphere, AWS, and Azure environments.

### Release note

```release-note
Add 0.12.1 Pinniped package to bring in bug fix release for an incompatibility between the Pinniped CLI and Chrome v98+ that causes browser-based logins to fail.
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by ankeesler — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
> @ankeesler:  /test install-vc7
Commit: 6bbb4f1

Tests failed! Build no: 1498

**Comment by alfredthenarwhal** [comment]
> @sabbey37:  /test install-vc7
Commit: 6bbb4f1

Build failed! Build no: 1497

**Comment by alfredthenarwhal** [comment]
> @sabbey37:  /test install-vc7
Commit: 6bbb4f1

Tests passed! Build no: 1504

**Comment by alfredthenarwhal** [comment]
> @sabbey37:  /test install-vc7
Commit: 2517997

Tests failed! Build no: 1519

**Comment by sabbey37** [comment]
> > @sabbey37:  /test install-vc7
> > Commit: [2517997](https://github.com/vmware-tanzu/tanzu-framework/commit/25179970e1a3c12879b076c8c7d3192556282b45)
> 
> Tests failed! Build no: 1519

This ultimately passed, but running it again for display purposes.

**Comment by alfredthenarwhal** [comment]
> @sabbey37:  /test install-vc7
Commit: 2517997

Tests passed! Build no: 1522

**Comment by alfredthenarwhal** [comment]
> @sabbey37:  /test install-vc7
Commit: 60ddd9d

Tests failed! Build no: 1527

**Pull request merged**
