### PR TITLE
add tolerations to aad pod identity

### LINKED ISSUE #3946: Missing control plane toleration for aad-pod-identity
**Bug description**
The aad-pod-identity component does not have a control plane toleration which means the DaemonSet pods of capz-nmi will not be scheduled to the control plane nodes.
But the capz controller manger has the control plane taints that allow the pod to get scheduled to the the control plane node and in such situations when the capz controller manager get scheduled to the control plane node and the capz-nmi pod is not due to absence of toleration, the authentication with azure cloud will fail with token refresh error. 
**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
The aad-pod-identity has a capz-nmi DaemonSet which should have tolerations so that it is able to schedule pod on control plane node as weel.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**
Reported Downstream

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by sonasingh46**
Signed-off-by: Ashutosh Kumar <sonasingh46@gmail.com>

### What this PR does / why we need it

Add tolerations to aad-pod-identity component YAML.

CAPZ pods has control plane tolerations and this means that capz pod can get scheduled to control plane nodes. The aad-pod-identity does not have tolerations which can cause authentication issue if the capz pod gets scheduled to a ctonrol plane node. 
This PR adds control plane tolerations to aad pod identity so that the their pods can be scheduled to control plane nodes too.

### Which issue(s) this PR fixes

Fixes #3946 

### Release note

```release-note
None
```

#### Special notes for your reviewer

Tested this PR by building the cli binary and creating a bootstrap cluster. Observed that the capz-nmi DaemonSet has the required tolerations.

### CODE REVIEW

**Review by rajathagasthya — APPROVED** [review]

**Review by rajathagasthya — CHANGES_REQUESTED** [review]
Please fix lint errors and make sure CI is green. You might want to rebase on latest where CAPD tests are disabled.

**Comment by sonasingh46** [comment]
@rajathagasthya -- I believe the linter is not failing because of my PR. Let me know if you think otherwise. Anyways, I have rebased and pushed.

**Comment by sonasingh46** [comment]
Will see if the lint fails again and figure out the problem.

**Comment by sonasingh46** [comment]
I see the yamllint problem -- may be I missed seeing that. My bad. 
Let me fix those.

**Review by rajathagasthya — APPROVED** [review]

**Pull request merged**
