### PR TITLE
[release-0.11] Configure vSphere CPI to exclude kube-vip IP

### PR DESCRIPTION
**Pull request by christianang**
### What this PR does / why we need it

**Main branch PR:** https://github.com/vmware-tanzu/tanzu-framework/pull/1480

This backports the kube-vip exclusion fix to the release-0.11 branch. Prevents the assignment of the kube-vip IP to a node's IP.

Bumps the vsphere-cpi from 1.22.4 to 1.22.6 in pkg/v1/providers, a pre-requisite for this feature.

### Which issue(s) this PR fixes

n/a

### Describe testing done for PR

Ran the provider unit tests locally. 

Ran install-vc7 e2e tests.

### Release note

```release-note
Prevent the vsphere-cpi from assigning the VSPHERE_CONTROL_PLANE_ENDPOINT IP to node's ExternalIP when running kube-vip.
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

This is an amended cherry-pick. The original commit depended features within a newer version of ytt e.g `assert.try_to` and ip parsing, which isn't available in the 0.11 branch. The code now uses regex to conditionally check if the `VSPHERE_CONTROL_PLANE_ENDPOINT` is ipv4 or ipv6.

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @christianang:  /test install-vc7
Commit: 0c21fc1

Tests failed! Build no: 1756

**Comment by navidshaikh** [comment]
> Tests failed! Build no: 1756

@christianang: Currently the test integration would test the changeset against latest zshippable graph (against main branch). `release-0.11` branch has different mapping of release-graph, so not applicable for PRs against `release-0.11`.

**Comment by christianang** [comment]
Thanks, I figured this may be the case. We will test it another way.

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: d470c3f

Tests failed! Build no: 1770

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: d470c3f

Tests passed! Build no: 1771

**Review by mcwumbly — APPROVED** [review]

**Pull request merged**
