### PR TITLE
Adding default fields check to avoid AntreaConfig creation

### PR DESCRIPTION
**Pull request by knabben**
### What this PR does / why we need it
Due to wrong validation of the fields on `antrea_config_exists` the AntreaConfig is always being created, to avoid this check the default of all fields before creating a new one.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-vc7
Commit: 4736449

Build failed! Build no: 3337

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-aws
Commit: 4736449

Build failed! Build no: 3341

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-vc7
Commit: 4736449

Tests passed! Build no: 3340

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-aws
Commit: 4736449

Tests failed! Build no: 3343

**Review by DanielXiao — APPROVED** [review]

**Review by shyaamsn — APPROVED** [review]

**Pull request merged**
