### PR TITLE
Fix AWS CC patch AWS_KCPT

### PR DESCRIPTION
**Pull request by saimanoj01**
### What this PR does / why we need it
Fix AWS CC patch AWS_KCPT

Issue seen with the template - 
```
replace operation does not apply: doc is missing key: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/imageRepository: missing value
```

Here is the kcp yaml and I see that those fields with null values are automatically removed. 

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by tenczar — APPROVED** [review]
LGTM

**Comment by vuil** [comment]
@saimanoj01 can you provide a little detail as to why we need this and what tests were done?

**Review by vuil — APPROVED** [review]
lgtm

**Comment by vuil** [comment]
lgtm, rerunning failed test, but @saimanoj01 reminder to add a description before merging.

**Pull request merged**
