### PR TITLE
Changing Clusterbootstrap.yaml with AntreaConfig CRD hooking

### LINKED ISSUE #3712: Missing fields on AntreaConfig CRD
**Bug description**
AntreaConfig CRD mismatches clusterbootstrap.yaml template.

**Affected product area (please put an X in all that apply)**

- (x) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
To have both sides match, AntreConfig and clusterbootstrap template

### PR DESCRIPTION
**Pull request by knabben**
### What this PR does / why we need it
Changes in the Clusterbootstrap.yaml, adding the missing AntreaConfig CRD fields and hooking the configuration variables from user settings.

The change in the clusterbootstrap must wait for #3749 to get merged with the CRD fields first.

### Which issue(s) this PR fixes

Fixes #3712

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2986

**Comment by knabben** [comment]
//usebom:sandbox/v1.7.0-zshippable/430795229814065281/tkg-compatibility:v12

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 3009

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 3034

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 3043

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 3073

**Comment by knabben** [comment]
//usebom:sandbox/v1.7.0-zshippable/431703182511446831/tkg-compatibility:v12

**Comment by knabben** [comment]
//usebom:sandbox/v1.7.0-zshippable/432478495243795787/tkg-compatibility:v12

**Comment by alfredthenarwhal** [comment]
Tests failed! Build no: 3079

**Review by 12345lcr — DISMISSED** [review]
I guess this pr should be based on the changes in https://github.com/vmware-tanzu/tanzu-framework/pull/3749/files, right? Some of the fields are undefined based on the error logs in the pr pipelines

**Pull request closed without merging**
