### PR TITLE
package/management: tanzu-auth package fixes for build

### PR DESCRIPTION
**Pull request by ankeesler**
```
We want it to be in bundle/config so that it will get picked up if someone runs
"ytt -f path/to/tanzu-auth/bundle/config".

Signed-off-by: Andrew Keesler <akeesler@vmware.com>
```

```
    This is to support our build system. We need a default image so that
    we can replace it with kbld.

    Signed-off-by: Andrew Keesler <akeesler@vmware.com>
```

### What this PR does / why we need it

* This was causing CI failures
* Specifically, this is blocking https://github.com/vmware-tanzu/tanzu-framework/pull/2355 from getting through CI

### Which issue(s) this PR fixes

None

### Describe testing done for PR

* I ran `ytt -f packages/management/tanzu-auth/bundle/config` and made sure it worked
* I am going to let CI do the rest of the testing for me

### Release note

```release-note
NONE
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

None

#### Special notes for your reviewer

None

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @ankeesler:  /test install-vc7
Commit: f2e06c9

Tests failed! Build no: 1998

**Review by prkalle — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
