### PR TITLE
WIP:provider: [PSA] Remove the overlay to initialize apiserver/extraVolumes empty array for CAPZ

### PR DESCRIPTION
**Pull request by ramineni**
### What this PR does / why we need it
The PR https://github.com/vmware-tanzu/tanzu-framework/pull/3862 , adds overlay to initialize the apiServer/extraVolumes array for all providers. This is replacing the extraVolumes defined in base.yaml ( https://github.com/vmware-tanzu/tanzu-framework/blob/main/packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml ) causing management cluster create to fail. This PR is to fix the same, remove initializing extraVolumes array for infrastructure-azure.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by wjun** [comment]
@ramineni Please double check if the jsonpatch in the extra secret will make all other jsonpatches in base.yaml, for example,  https://github.com/vmware-tanzu/tanzu-framework/blob/main/packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml invalid anymore?

**Comment by ramineni** [comment]
> @ramineni Please double check if the jsonpatch in the extra secret will make all other jsonpatches in base.yaml, for example, https://github.com/vmware-tanzu/tanzu-framework/blob/main/packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml invalid anymore? You could also have a look at the live environment in tkg-15461.

@wjun Thanks for the review. As checked again in the live env , it is appending to the existing array and not changing the existing patches. I have updated to add the empty array only for capd provider as other providers do have initialized in the base template.

**Comment by ramineni** [comment]
@tenczar PTAL

**Review by wjun — APPROVED** [review]
LGTM

**Pull request closed without merging**
