### PR TITLE
[release-0.11 cherrypick] Fixes for airgap custom certificate issues

### PR DESCRIPTION
**Pull request by blc1996**
### What this PR does / why we need it
Cherrypicking airgap certificate fixes to release-0.11 branch
* Fix kapp controller file access issue and bump kapp controller to 0.30.1 https://github.com/vmware-tanzu/tanzu-framework/pull/1733
* Fix TKR custom certificate issue in imgpkg library https://github.com/vmware-tanzu/tanzu-framework/pull/1804

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

- [ ] Manually setup a airgap env with custom certificate and tested

### Release note

```release-note
Fix the issue for unable to use custom certificate in an airgap environment
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by vuil** [comment]
nit: weird that there is a checkbox in "Describe testing done for PR" or did you truly mean to indicate that is something that has yet to be completed?
Please add and entry to the Release notes section as well.

**Comment by blc1996** [comment]
> nit: weird that there is a checkbox in "Describe testing done for PR" or did you truly mean to indicate that is something that has yet to be completed? Please add and entry to the Release notes section as well.

Prem and I did manual testing specific for kapp-controller and tkr-controller regarding using custom cert, and both works as expected.

That checkbox is meant for setting up an airgap env and have a e2e test for clusterbootstrap. We are working on it today, and will probably get a conclusion tmr.

**Review by vijaykatam — APPROVED** [review]
kapp-controller changes look good to me

**Review by prkalle — APPROVED** [review]
imgpkg registry changes look good to me.

**Comment by blc1996** [comment]
Hi @vuil , could you take a look and merge it if it looks good? I don't have the privilege to merge.

**Review by vuil — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
