### PR TITLE
packages/management/framework: add tanzu-auth package

### PR DESCRIPTION
**Pull request by ankeesler**
Signed-off-by: Andrew Keesler <akeesler@vmware.com>

### What this PR does / why we need it

* Adds the `tanzu-auth` package to the tanzu framework composite package

### Which issue(s) this PR fixes

None

### Describe testing done for PR

None

### Release note

```release-note
NONE
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

* See https://github.com/vmware-tanzu/tanzu-framework/pull/2219 for where we create the tanzu-auth package

#### Special notes for your reviewer

None

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @ankeesler:  /test install-vc7
Commit: b094fae

Tests failed! Build no: 1901

**Comment by alfredthenarwhal** [comment]
> @ankeesler:  /test install-vc7
Commit: b094fae

Tests failed! Build no: 1906

**Comment by alfredthenarwhal** [comment]
> @sabbey37:  /test install-vc7
Commit: ef8a90b

Tests failed! Build no: 1962

**Comment by alfredthenarwhal** [comment]
> @sabbey37:  /test install-vc7
Commit: f1fb065

Tests failed! Build no: 1965

**Review by sabbey37 — APPROVED** [review]

**Review by miclettej — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
> @sabbey37:  /test install-vc7
Commit: e0b0ce1

Tests failed! Build no: 1988

**Pull request merged**
