### PR TITLE
Make secret plugin a separate go module

### LINKED ISSUE #3351: Make Secret plugin a separate go module
**Describe the feature request**
Currently Secret plugin is using common tanzu-framework go.mod file for build. We should decouple that and create a separate go.mod file within plugin directory, so as to facilitate future move of the secret plugin to its own repository. 

**Describe alternative(s) you've considered**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (X) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- (X) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Additional context**

### PR DESCRIPTION
**Pull request by maralavi**
Signed-off-by: Marjan Alavi <malavi@vmware.com>

### What this PR does / why we need it
Make secret plugin a separate go module

TODO: Will remove package plugin go.mod once https://github.com/vmware-tanzu/tanzu-framework/pull/3316 got merged (due to dependency of tests on secret plugin, needed those files in order to send PR)

### Which issue(s) this PR fixes

Fixes #3351 

### Describe testing done for PR
Ran make build-install-cli-local and verified the ```secret plugin``` commands were working. 

### Release note

```release-note
None
```

### CODE REVIEW

**Review by marckhouzam — COMMENTED** [review]
This looks great.  Just a couple of suggestions:

1. Plugins now have their own `buildinfo` so they don't need to depend on Framework's main module.  So in `secret/main.go` you can change the import `github.com/vmware-tanzu/tanzu-framework/pkg/v1/buildinfo` to `github.com/vmware-tanzu/tanzu-framework/cli/runtime/buildinfo` 
2. I also see that `github.com/vmware-tanzu/tanzu-framework/pkg/v1/sdk/capabilities/discovery` is newly available in `github.com/vmware-tanzu/tanzu-framework/cli/core/pkg/cluster/discovery` which is outside of Framewor's main module.  You can probably change the import of `secret/main.go`.

If you make the above two changes, I believe you will no longer depend on Framework's main module and you can remove both the `replace` and the `require` of `github.com/vmware-tanzu/tanzu-framework` from your new `go.mod`

**Comment by maralavi** [comment]
> This looks great. Just a couple of suggestions:
> 
> 1. Plugins now have their own `buildinfo` so they don't need to depend on Framework's main module.  So in `secret/main.go` you can change the import `github.com/vmware-tanzu/tanzu-framework/pkg/v1/buildinfo` to `github.com/vmware-tanzu/tanzu-framework/cli/runtime/buildinfo`
> 2. I also see that `github.com/vmware-tanzu/tanzu-framework/pkg/v1/sdk/capabilities/discovery` is newly available in `github.com/vmware-tanzu/tanzu-framework/cli/core/pkg/cluster/discovery` which is outside of Framewor's main module.  You can probably change the import of `secret/main.go`.
> 
> If you make the above two changes, I believe you will no longer depend on Framework's main module and you can remove both the `replace` and the `require` of `github.com/vmware-tanzu/tanzu-framework` from your new `go.mod`

Thanks @marckhouzam I believe the ```github.com/vmware-tanzu/tanzu-framework/cli/core/pkg/cluster/discovery``` has got available pretty recently and I was unaware of that. thanks for letting me know. I just made the change :)

**Comment by marckhouzam** [comment]
> Thanks @marckhouzam I resolved `buildinfo`, but about `discovery` module, I just checked with @prkalle Seems like we should avoid in our modules to depend on tanzu cli core packages. We still have reliance on Tanzu Framework until #3260 get merged

That is true.  My mistake.  Thanks for checking!

**Review by marckhouzam — APPROVED** [review]
LGTM

**Review by danniel1205 — APPROVED** [review]
lgtm, thanks for the refactoring work

**Review by codegold79 — APPROVED** [review]
Thanks so much for finishing the plugin/package part of refactoring. Great work on this whole modularizing secrets and package plugins work!

**Review by adduarte — APPROVED** [review]

**Pull request merged**
