### PR TITLE
Load all credential helpers

### PR DESCRIPTION
**Pull request by scothis**
### What this PR does / why we need it

Any place we load one of the k8s credential helpers, load them all.
Since we don't know what clusters users will use Tanzu with, we need to
support everything.

### Which issue(s) this PR fixes

A user reported being unable to use the `tanzu package` cli plugin with TKGi

```
Error: Unable to set up rest mapper: no Auth Provider found for name "oidc"
Error: exit status 1
```

### Release note

```release-note
Load all kubernetes credential helpers
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by maralavi** [comment]
Question: Does the following file needs change as well?
https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v2/tkr/webhook/infra-machine/main.go#L13

**Comment by maralavi** [comment]
@scothis Thanks for the PR. You need to resolve the conflict for the ```addons/go.mod``` and the above question I left. Otherwise, the PR looks good to me.

**Comment by shivaani0505** [comment]
PR looks good to me. Please resolve conflicts for go.mod.

**Comment by scothis** [comment]
rebased

**Review by maralavi — APPROVED** [review]

**Comment by danniel1205** [comment]
Thanks for the PR. @scothis could you help add `Describe testing done for PR` in PR description ? Thanks

**Comment by scothis** [comment]
The short answer is "none", other than my current usage of the cli didn't break. I don't have the bandwidth to fully test oidc. If someone else who has access to a cluster can test it out, that would be appreciated.

**Comment by vijaykatam** [comment]
Unless I am missing something this change removes gcp auth since root import only does oidc https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/plugins.go.

Is that expected since gcp k8s 1.25 is [dropping support](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke) for this plugin? https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/gcp/gcp.go#L120

**Review by vijaykatam — APPROVED** [review]
Approved with the caveat that only tested on OIDC. Not tested on GCP.

**Pull request merged**
