### PR TITLE
Adding cni from vars on vsphere template

### LINKED ISSUE #4281: CNI variable is not imported on vsphere template
**Bug description**
`get_vsphere_vars` is filtering the variables imported in the Cluster object, `cni` is not in the list and must be added to be rendered in the cluster object. This affects json in line patches and functions that rely on this variable.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- (x) Installation
- (x) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
To have data.values.CNI imported in the variables list

**Steps to reproduce the bug**
Set a CNI: none and observe the Cluster object having cni: antrea as variable.

**Version** (include the SHA if the version is not obvious)
2.1

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by knabben**
### What this PR does / why we need it
This PR is a sequence of steps to enable Windows nodes without a default CNI installed.
- The `cni` variable is not ACL in the template, thus continually rendering the default. This PR adds to the list.
- Moving the json patch to disable the firewall outside the Antrea installation, allowing the user SSH access when `CNI:none`

### Which issue(s) this PR fixes

Fixes #4281

### Describe testing done for PR

Tests were made on a local ClusterClass on vsphere 7

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-vc7
Commit: b81d4e2

Tests failed! Build no: 3831

**Comment by lubronzhan** [comment]
Question, saw you move the firewall option, does it also need to move the adding ctr and containerd to defender option?

**Comment by knabben** [comment]
> Question, saw you move the firewall option, does it also need to move the adding ctr and containerd to defender option?

Moving to get this behavior outside of Antrea installations, the correct port usage review is planned, for the MS Defender they are already being excluded in the image-builder process. i.e.

https://github.com/kubernetes-sigs/image-builder/blob/0bb5cd6db390516c75daeeaf27f19b1aa958428b/images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml#L87

**Review by lubronzhan — APPROVED** [review]

**Comment by knabben** [comment]
//usebom:sandbox/v2.1.0-zshippable/442935805833406440/tkg-compatibility:v12

**Pull request merged**
