### PR TITLE
[DO-NOT-MERGE] TESTS: Discover Plugins from all active contexts and Support Plugin Name conflicts across different Targets

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it

Creating a new PR from the branch on this repo. PR is same as #3961 and has been created to verify the pipeline runs when PR is created from branch on this repo.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @anujc25:  /test install-vc7
Commit: 4cabafc

Tests failed! Build no: 3404

**Comment by anujc25** [comment]
//usebom:v20-v1.7.0-zshippable/tkr-compatibility:v20

**Comment by alfredthenarwhal** [comment]
> @anujc25:  /test install-vc7
Commit: 5221503

Build failed! Build no: 3409

**Comment by alfredthenarwhal** [comment]
> @anujc25:  /test install-vc7
Commit: fea415e

Build failed! Build no: 3410

**Pull request closed without merging**
