### PR TITLE
Remove reference to tanzu-framework-addons in providers

### PR DESCRIPTION
**Pull request by blc1996**
Signed-off-by: Lucheng Bao <luchengb@vmware.com>

### What this PR does / why we need it

`tanzu-framework-addons` is going to be removed from TKR as a component. Thus, removing all references pointing to this component in Providers.

- CPI app manifest is not used
- function `tanzuaddonsmanagerimageinfodatavalues` is not used
- We will not allow creating C.0 clusters in Dakar, removing Pinniped image info as backward compatibility with C.1 isn't needed anymore.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note
None
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @blc1996:  /test
Commit: ebfac2d

Tests failed! Build no: 1007

**Review by ankeesler — APPROVED** [review]
pinniped changes seem reasonable to me. thanks for doing this

**Comment by alfredthenarwhal** [comment]
> @blc1996:  /test
Commit: ebfac2d

Tests failed! Build no: 1009

**Comment by alfredthenarwhal** [comment]
> @blc1996:  /test
Commit: ebfac2d

Tests failed! Build no: 1020

**Pull request closed without merging**
