### PR TITLE
bump ClusterAPI to v1.2.8

### PR DESCRIPTION
**Pull request by ykakarap**
### What this PR does / why we need it

This PR bumps ClusterAPI version to v1.2.8 

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.7.0-zshippable/438896197478949414/tkg-compatibility:v12

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.7.0-zshippable/439469939946952695/tkg-compatibility:v12

**Review by jeffwubj — APPROVED** [review]

**Comment by ykakarap** [comment]
Rebasing to address conflicts.

**Review by wjun — APPROVED** [review]
LGTM

**Pull request merged**
