### PR TITLE
Add single quote to ca cert related preKubeadmCommands to make sure w…

### PR DESCRIPTION
**Pull request by lubronzhan**
…hole command is executed

### What this PR does / why we need it
Currently, the `preKubeadmCommands` that with `||` will not be executed if it's not quoted.

### Which issue(s) this PR fixes

Fixes #https://github.com/vmware-tanzu/tanzu-framework/issues/2720

### Describe testing done for PR

Manually copy over the overlay to tanzu cli to create cluster, and ssh into vm then check if CA store adds this certificate

### Release note

```release-note

```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by vuil** [comment]
Thanks for the changes @lubronzhan 
@tenczar PTAL.

**Comment by tenczar** [comment]
LGTM

**Review by HanFa — APPROVED** [review]
Lgtm

**Review by vuil — APPROVED** [review]
lgtm, thanks

**Pull request merged**
