### PR TITLE
List context server name in `plugin source list`

### LINKED ISSUE #1472: tanzu plugin source command not listing all sources
**Bug description**

The command `tanzu plugin source list` is not showing all sources, it's not showing the source 'default-tkg-mgmt-vsphere-*' for the Context scope plugins.

>./tanzu-core-darwin_amd64 plugin source list
NAME     TYPE  SCOPE
default  oci   Standalone
>./tanzu-core-darwin_amd64 plugin list                    
NAME                DESCRIPTION                                                        SCOPE       DISCOVERY                                VERSION      STATUS
cluster             Kubernetes cluster operations                                      Context     default-tkg-mgmt-vsphere-20220104173410  v0.15.0-dev  installed
kubernetes-release  Kubernetes release operations                                      Context     default-tkg-mgmt-vsphere-20220104173410  v0.15.0-dev  installed
login               Login to the platform                                              Standalone  default                                  v0.14.0      update available
management-cluster  Kubernetes management-cluster operations                           Standalone  default 

In the above output, the `tanzu plugin source list` does not show the 'default-tkg-mgmt-vsphere-20220104173410' same we can see in the `tanzu plugin list` output.
Commands reference doc: https://github.com/vmware-tanzu/tanzu-framework/blob/f954704609c8102d657f6fe9a20b0b7515f53e23/docs/cli/cli-architecture.md
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
the 'tanzu plugin source' should list all available sources, all the DISCOVERY types in 'tanzu plugin list' should be part of the 'tanzu plugin source' output.

**Steps to reproduce the bug**
1. Run command `tanzu plugin list`, make sure it has at least one Context SCOPE.
2. Now run `tanzu plugin source list`, you can see Context scope DISCOVERY not part of previous step output.

**Version** (include the SHA if the version is not obvious)
v0.14.0
**Environment where the bug was observed (cloud, OS, etc)**
All OS's
**Relevant Debug Output (Logs, manifests, etc)**
NA

### PR DESCRIPTION
**Pull request by chandrareddyp**
Allows to list Context-aware plugin source's for command `tanzu plugin source list`

### Which issue(s) this PR fixes

Fixes #1472 

### Describe testing done for PR

In the `tanzu plugin source list` flow, When the Discovery source is empty for the current server, then it generates the discovery source based on other parameters, which are already implemented, we are reusing it in this flow.

### Release note

```NONE```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by stmcginnis** [comment]
Running locally fine. Default base install has no errors listing plugin source:

```txt
❯ tanzu plugin source list
  NAME           TYPE   SCOPE
  default-local  local  Standalone
  admin-local    local  Standalone
```

**Review by stmcginnis — APPROVED** [review]
lgtm

**Comment by stmcginnis** [comment]
BTW, looks like you may need to update your signing git config. I don't think this is your actual email address, and you authored, not co-authored, this patch.

`Co-authored-by: Chandra Pamuluri <cpamuluri@cpamuluri-a01.vmware.com>`

**Comment by chandrareddyp** [comment]
> . Default base install has no errors listing plugin so

It happens only when `tanzu` referring a Context-specific server.

**Pull request merged**
