### PR TITLE
Azure Omnibus Bug Fixes

### LINKED ISSUE #2798: kube-controller-manager attempts to update routetable in Azure with duplicate routes after upgrade
**Bug description**
The in-tree route controller attempts to add a route to an Azure route table with the same CIDR range as the existing route from an old control plane node. This spams the controller manager logs with the 400 errors received from Azure resource manager. 

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [X] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience

**Expected behavior**
The route controller is not necessary for these cluster builds in Azure and should be disabled.

**Steps to reproduce the bug**
Deploy a 1.21.x CAPZ cluster and upgrade to 1.22.x

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**
Azure, Ubuntu

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by randomvariable**
Omnibus PR of #4254, #4250 and #4259

Fixes: #2798
Partial fix for #2777

### Release note

```release-note
* Azure: Disable use of AAD Pod Identity for resolution of Azure credentials
* Azure: Restart pods during private cluster initialisation to work around lack of hairpin LB support for control planes
* Azure: Disable extraneous route table entries
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @randomvariable:  /test install-azure
Commit: b91b570

Tests failed! Build no: 3837

**Review by sonasingh46 — APPROVED** [review]

**Review by yastij — APPROVED** [review]

**Comment by sonasingh46** [comment]
@wjun -- Can you help merging this? Have re triggered the integration test.

**Comment by alfredthenarwhal** [comment]
> @wjun:  /test install-azure
Commit: 4395000

Tests failed! Build no: 4024

**Review by wjun — APPROVED** [review]
capz cc pipeline passed. capz mgmt cluster creation passed. downstream install-azure failed twice during build phase because of unrelated component sandbox build failure.

**Pull request merged**
