### PR TITLE
update antreaConfig crd as some new members are added to CRD

### PR DESCRIPTION
**Pull request by liu4480**
since antrea 1.9 has options for TunnelPort,TunnelCsum and TopologyAwareHints. But it seems antreaconfig does not include the properties in crd defination in pr https://github.com/vmware-tanzu/tanzu-framework/pull/4481

### Which issue(s) this PR fixes
with [https://github.com/vmware-tanzu/tanzu-framework/pull/4481 ,](https://github.com/vmware-tanzu/tanzu-framework/pull/4481) antreaConfig should support TunnelPort,TunnelCsum and TopologyAwareHints

define antreaConfig like:
```
apiVersion: cni.tanzu.vmware.com/v1alpha2
kind: AntreaConfig
metadata:
name: xxx
namespace: default
spec:
antrea:
config:
tunnelPort: 9999
```
got the following error:

`Error from server (BadRequest): error when creating "an.yaml": AntreaConfig in version "v1alpha2" cannot be handled as a AntreaConfig: strict decoding error: unknown field "spec.antrea.config.tunnelPort"`

Fixes #TKG-19288

### Describe testing done for PR

manually tested on a Living TKG env

### Release note

```release-note

```

### CODE REVIEW

**Comment by edwardbadboy** [comment]
Better to use a more formal capitalization in PR and commit title: `Add New Members to AntreaConfig CRD`, and explain why need to add new members in commit message (because we missed them in previous patch).

**Review by edwardbadboy — APPROVED** [review]
Hello @hangyan , can you confirm that the newly exposed members in this patch is supported in Antrea 1.9 Package?

**Comment by knabben** [comment]
@liu4480 please provide a proper description, it will help in the review process

**Comment by hangyan** [comment]
> Hello @hangyan , can you confirm that the newly exposed members in this patch is supported in Antrea 1.9 Package?

yes

**Review by knabben — APPROVED** [review]

**Review by lubronzhan — APPROVED** [review]

**Comment by hangyan** [comment]
@wjun can you help review and merge this?

**Pull request merged**
