### PR TITLE
fix cluster upgrade error when node network list is empty

### PR DESCRIPTION
**Pull request by XudongLiuHarold**
Signed-off-by: Xudong Liu <xudongl@vmware.com>

### What this PR does / why we need it

- fix upgrade error when node network list is empty

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note
none
```

### CODE REVIEW

**Review by chenlin07 — APPROVED** [review]
lgtm

**Comment by alfredthenarwhal** [comment]
> @XudongLiuHarold:  /test install-vc7
Commit: 1821b0e

Tests failed! Build no: 4051

**Review by lubronzhan — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
> @XudongLiuHarold:  /test install-vc7
Commit: 7b3231c

Tests failed! Build no: 4074

**Pull request merged**
