### PR TITLE
Add control-plane toleration to capabilities manager

### PR DESCRIPTION
**Pull request by seemiller**
### What this PR does / why we need it

There is a [long running effort](https://github.com/kubernetes/kubeadm/issues/2200) to rename `node-role.kubernetes.io/master` to `node-role.kubernetes.io/control-plane`. This PR adds the `node-role.kubernetes.io/control-plane` toleration to capabilities manager.

A future PR will issued to remove the offensive `node-role.kubernetes.io/master` toleration.

### Describe testing done for PR

Ran the task `make test` in the capabilities directory.

### Release note

```release-note
Add the `node-role.kubernetes.io/control-plane` toleration to capabilities manager.
```

### CODE REVIEW

**Review by codegold79 — APPROVED** [review]
lgtm

**Comment by alfredthenarwhal** [comment]
Tests failed! Build no: 2819

**Comment by codegold79** [comment]
I'm not sure how to fix it, but I encountered this in my PR #3489 where running YTT does not generate the new toleration item:

```
$ ytt --ignore-unknown-comments -f packages/capabilities/bundle/config
...
apiVersion: apps/v1
kind: Deployment
...
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
```

**Comment by alfredthenarwhal** [comment]
Tests canceled! Build no: 2891

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2892

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2894

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2895

**Review by danniel1205 — APPROVED** [review]
lgtm, thanks for the PR

**Pull request merged**
