### PR TITLE
Bump Cluster API and providers

### PR DESCRIPTION
**Pull request by ykakarap**
### What this PR does / why we need it

This PR bumps the version of ClusterAPI and the providers.

Go dependencies will be merged in https://github.com/vmware-tanzu/tanzu-framework/pull/3157

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.7.0-zshippable/430495289984455744/tkg-compatibility:v12

**Comment by wjun** [comment]
Please fix the errors in main/build pipeline.

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.7.0-zshippable/430679015683004628/tkg-compatibility:v12

**Comment by randomvariable** [comment]
rebased

**Comment by ykakarap** [comment]
>rebased

Thank you!

**Review by randomvariable — APPROVED** [review]

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.7.0-zshippable/430776759441430622/tkg-compatibility:v12

**Comment by srm09** [comment]
Removed the CAPA 2.0.0 bump from the patch. Also, removed the fixes for the pipelines made for the CAPA bumps.

**Comment by srm09** [comment]
Will eventually close this in favor of #3752 
/hold

**Comment by ykakarap** [comment]
Closing this PR in favor of https://github.com/vmware-tanzu/tanzu-framework/pull/3772

**Pull request closed without merging**
