### PR TITLE
Create a top-level directory for provider template

### LINKED ISSUE #3624: Create a top-level directory for provider template
**Describe the feature request**

**Describe alternative(s) you've considered**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Additional context**

### PR DESCRIPTION
**Pull request by Vandy-P**
Moving pkg/v1/providers to top level

Signed-off-by: Vandana Pathak <pathakv@sjc-ubu-eng-127.vmware.com>

### What this PR does / why we need it

Create a top-level directory for provider template

### Which issue(s) this PR fixes

Fixes #3624 

### Describe testing done for PR

- Tested all the target in provider/Makefile
- Tested clustergen 
        -  Since providers path in main branch is pkg/v1/providers and after providers refactoring its moved to top level directory tanzu-framework/providers , to test clustergen we made temporary path changes to run clustergen between this branch and main branch.
        - Tested locally (after adjusting providers path in ./hack/clustergen/ci-validate-clustergen.sh )
              CLUSTERCTL=clusterctl CLI_REPO=$PWD ./hack/clustergen/ci-validate-clustergen.sh refs/pull/3626/merge main
        - Tested git pipeline CI via following PR 
             https://github.com/vmware-tanzu/tanzu-framework/pull/3626   (PR is raised against main branch with one line changes in providers/infrastructure-aws/v1.2.0/yttcc/overlay.yaml file)
            

### Release note

```Create a top-level directory for provider template```

### CODE REVIEW

**Comment by Vandy-P** [comment]
//usebom:sandbox/v1.7.0-zshippable/427460516659595194/tkg-compatibility

**Review by tenczar — APPROVED** [review]
I noticed that there are several files that appear as new files in the addon/vendir directory. Should those files exist as new files?

**Comment by Vandy-P** [comment]
> I noticed that there are several files that appear as new files in the addon/vendir directory. Should those files exist as new files?

  Those files are taking care off , issue was with move .

**Comment by vuil** [comment]
>cluster-generation-diffs / cluster-check.sh - Didn't find the usage , need to dig in more. Please can you help here , how to test clustergen target?

Please see pkg/v1/providers/tests/clustergen/README.md
by default `make clustergen`will test the effect of cluster configuration generation based on code built without (before) and with (after) the topmost commit. You can configure the "before" commit to point to anything in the commit history.
The output of the test is in pkg/v1/providers/test/clustergen/testdata/

As part of this PR we should ensure that the test output produced by 'make clustergen' is unchanged when compared to that produced prior to the refactoring.

**Comment by Vandy-P** [comment]
> Cluster Generation A/B Results:



> Thanks for the changes @Vandy-P !
> 
> > cluster-generation-diffs / cluster-check.sh - Didn't find the usage , need to dig in more. Please can you help here , how to test clustergen target?
> 
> Please see pkg/v1/providers/tests/clustergen/README.md by default `make clustergen`will test the effect of cluster configuration generation based on code built without (before) and with (after) the topmost commit. You can configure the "before" commit to point to anything in the commit history. The output of the test is in pkg/v1/providers/test/clustergen/testdata/
> 
> As part of this PR we should ensure that the test output produced by 'make clustergen' is unchanged when compared to that produced prior to the refactoring.

Hi @vuil , will the "Cluster Generation A/B Results:" in PR pipe line is sufficient for this testing ?

**Comment by Vandy-P** [comment]
//usebom:sandbox/v1.7.0-zshippable/427460516659595194/tkg-compatibility

**Comment by Vandy-P** [comment]
> @Vandy-P there are some unit test failures that looks related to the change itself.
> 
> Because the destination of the clustergen outputs has changed due to the PR, the diffing done to show the effects of this PR is in the test PR [3567](https://github.com/vmware-tanzu/tanzu-framework/pull/3567) was not effective. Can you nonetheless fill in the testing done section to indicate if you used any alternative means to ensure that the clustergen outputs were not affected by this change?
> 
> It would be helpful that we file an issue and reference it in this PR.

Done

**Review by vuil — APPROVED** [review]
LGTM. Thanks @Vandy-P for persisting on the clustergen-related verification.
Approved; will remove do-not-merge/hold once change is rebased and passing all checks.

**Review by randomvariable — APPROVED** [review]

**Comment by vuil** [comment]
>

**Comment by vuil** [comment]
> Have we also checked embedding the providers in the cluster and management cluster plugins still works?
Yes, from the makefile changes and testing locally, I verified the embedding still works as before.

fatfingered :-(. Meant to cancel a comment, but closed the PR instead. Reopened.

**Comment by vuil** [comment]
Also: fatfingered :-(. Meant to cancel a comment, but closed the PR instead. Reopened, and merging now.

**Pull request merged**
