### PR TITLE
Fix getting AWSCluster through Cluster name

### PR DESCRIPTION
**Pull request by 12345lcr**
### What this PR does / why we need it
* Fix getting AWSCluster through Cluster name instead of Cluster InfrastructureRef when checking and updating the AWSIngressRule for kapp-controller and addons-controller.
* Fix the cluster's infrastructure check through InfrastructureRef instead of the existence of cap<infra> namespace.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @12345lcr:  /test install-vc7
Commit: ba65aa2

Tests failed! Build no: 4040

**Review by wjun — APPROVED** [review]
LGTM.

**Comment by alfredthenarwhal** [comment]
Created cherry-pick PR

**Pull request merged**
