### PR TITLE
[Workaround]Schedule featuregate pod on controlplane nodes

### PR DESCRIPTION
**Pull request by 12345lcr**
### What this PR does / why we need it
Schedule featuregate pod on controlplane nodes by adding the nodeSelector to fix the CAPA ClusterClass CI.

This may not be the final solution since it may related to aws security group and node ports.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by danniel1205** [comment]
Thanks for the change. If adding NodeSelector is the fix, I think it could be added via https://github.com/vmware-tanzu/tanzu-framework/blob/main/packages/featuregates/bundle/config/values.yaml#L7

**Comment by 12345lcr** [comment]
Thanks @danniel1205 , just realized that this field is already defined in the overlay, I updated this part.

**Review by yharish991 — APPROVED** [review]
LGTM!!

**Comment by danniel1205** [comment]
Thanks for the PR, changes seem reasonable but it's worth a revisit. The CAPA is still failing but it is a different issue. After looking into the log, it does fix the featuregate deployment issue we saw earlier. So, I am adding my approval on this PR. Feel free to merge it if it blocks everyone, otherwise I would suggest hold on until 28th once folks are back from Thanksgiving holiday.

**Review by danniel1205 — APPROVED** [review]

**Comment by hongtaiwang** [comment]
should we add node selector for other packages with `hostNetwork: true` configured such as addonsManager and tanzuauth?

**Pull request merged**
