### PR TITLE
Adding missing fields in the AntreaConfig

### PR DESCRIPTION
**Pull request by knabben**
### What this PR does / why we need it
Adding missing fields on AntreaConfig, the second step should change the clusterbootstrap.yaml this PR gets merged

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 3036

**Review by 12345lcr — APPROVED** [review]
LGTM

**Review by jeffwubj — APPROVED** [review]

**Review by wjun — APPROVED** [review]

**Pull request merged**
