### PR TITLE
Enable MHC by default for vsphere/azure providers

### PR DESCRIPTION
**Pull request by wjun**
### What this PR does / why we need it
Enable MHC by default to be consistent to legacy behavior
### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
Azure integration tests. Bolt install-vc7 tests.

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @wjun:  /test install-vc7
Commit: 194aada

Tests failed! Build no: 3638

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7
Commit: 5faf008

Build failed! Build no: 3713

**Comment by alfredthenarwhal** [comment]
> @wjun:  /test install-vc7
Commit: 5faf008

Tests passed! Build no: 3722

**Review by DanielXiao — APPROVED** [review]

**Pull request merged**
