### PR TITLE
bumping kapp-controller's package to 0.38.3

### PR DESCRIPTION
**Pull request by ridavid2002**
### What this PR does / why we need it

* Bump kapp-controller to 0.38.3

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note
Bump kapp-controller to 0.38.3
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by ridavid2002** [comment]
//usebom:sandbox/v1.6.0-zshippable/413537630915922337/tkg-compatibility

**Comment by ridavid2002** [comment]
//usebom:sandbox/v1.6.0-zshippable/415253430639007445/tkg-compatibility

**Comment by ridavid2002** [comment]
//usebom:sandbox/v1.6.0-zshippable/415253430639007445/tkg-compatibility

**Comment by ridavid2002** [comment]
//usebom:sandbox/v1.6.0-zshippable/415259469866340647/tkg-compatibility

**Comment by vuil** [comment]
> @ridavid2002 @vijaykatam please consider to bump the kapp-controller version here as well
> 
> https://github.com/vmware-tanzu/tanzu-framework/blob/97213dc0005285690c08062a97b00080bcbbc768/hack/kind/deploy_kind_with_capi_and_kapp.sh#L19

@ridavid2002 PR merged. Let's address this in a followup.

**Pull request merged**
