### PR TITLE
Do not override imageRepository for every component in Kubernetes spec

### LINKED ISSUE #4178: TKR_DATA formation in tkr-resolver overrides ImageRepository for every component
**Bug description**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- (x) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
tkr-resolver takes Kubernetes spec from TKR yaml and then forms TKR_DATA. If TKR yaml provides imageRepository for a component, say kube-vip, then it should be reflected in TKR_DATA. In this case, it is overridden by customImageRepository https://github.com/vmware-tanzu/tanzu-framework/blob/main/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go#L333-L349 
**Steps to reproduce the bug**
Set imageRepository for any of etcd, coredns, kube-vip or pause in TKR yaml and create a management cluster. Notice TKR_DATA created by tkr-resolver. 
**Version** (include the SHA if the version is not obvious)
v0.28.0-dev
**Environment where the bug was observed (cloud, OS, etc)**
vsphere
**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by rajaskakodkar**
Signed-off-by: Rajas Kakodkar <rkakodkar@vmware.com>

### What this PR does / why we need it
fixes #4178 
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by rajaskakodkar** [comment]
cc: @imikushin

**Comment by alfredthenarwhal** [comment]
> @rajaskakodkar:  /test install-vc7
Commit: be64eaf

Tests failed! Build no: 3619

**Comment by imikushin** [comment]
Hey @rajaskakodkar, closing this, as well as #4178.

Appreciate all the effort you've put in to debug the issue.

**Pull request closed without merging**
