### PR TITLE
Add ownerRef to nsx-t and vsphere secret referred by vspherecpiconfig

### PR DESCRIPTION
**Pull request by lubronzhan**
### What this PR does / why we need it
Currently, the vsphere credentials and nsx-t credentials related to vspherecpi were created but without ownerRef, when cluster is deleted, they are left over.
So add ownerref to them.
Also infer the parameters from Cluster object as many as we can, instead of generating from cli.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7 --test-params "CLUSTER_TYPE:classy"
Commit: bd92234

Tests failed! Build no: 3507

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7
Commit: bd92234

Tests failed! Build no: 3515

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: b0c4c79

Build failed! Build no: 3522

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: cb33d5b

Tests failed! Build no: 3538

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 5cf1259

Tests failed! Build no: 3543

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 195beaf

Tests passed! Build no: 3566

**Review by danniel1205 — APPROVED** [review]
LGTM. Thanks for the change.

**Pull request merged**
