### PR TITLE
Move `apis/config/ClientConfig` and `apis/cli/Catalog` API to `cli/runtime/apis` module

### LINKED ISSUE #3369: Move `apis/config/ClientConfig` and `apis/cli/Catalog` API to `cli/runtime/apis` module
**Describe the feature request**

- `apis/config/ClientConfig` and `apis/cli/Catalog` API structs are actually used for storing client side configuration on the user's machine. Meaning this configurations are not used as CRDs on the server but just used to store, update and process client side configuration
- Considering this, above 2 APIs should not be part of root level `apis/` directory but should be part of CLI runtime library under `cli/runtime`

**Describe alternative(s) you've considered**
-

**Affected product area (please put an X in all that apply)**

- (x) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Additional context**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it
- `apis/config/ClientConfig` and `apis/cli/Catalog` API structs are actually used for storing client side configuration on the user's machine. Meaning this configurations are not used as CRDs on the server but just used to store, update and process client side configuration.
- This PR moves both 2 APIs from root level `apis/` directory to CLI runtime library under `cli/runtime`
- Also update references within the repository

### Which issue(s) this PR fixes

Fixes #3369

### Describe testing done for PR
- CI should validate the changes.
- Manually verified by running `make modules` , `make build-install-cli-local`

### Release note

```release-note
Move `apis/config/ClientConfig` and `apis/cli/Catalog` API to `cli/runtime/apis` module
```

### CODE REVIEW

**Review by marckhouzam — CHANGES_REQUESTED** [review]
Very nice.

I think we need to update the imports of `main.go.tmpl` but the rest looks great.

**Review by prkalle — COMMENTED** [review]
The changes look good.

**Review by marckhouzam — APPROVED** [review]
LGTM

Thanks 👍

**Review by prkalle — APPROVED** [review]

**Comment by vuil** [comment]
lgtm, thanks

**Review by vuil — APPROVED** [review]

**Pull request merged**
