### PR TITLE
Validation of kubevip lb

### PR DESCRIPTION
**Pull request by lubronzhan**
### What this PR does / why we need it
Add basic validation of kubevip lb parameters
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 8c9d95c

Tests passed! Build no: 3373

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: f95a305

Tests passed! Build no: 3378

**Review by randomvariable — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 0619fa0

Tests failed! Build no: 3416

**Pull request merged**
