### PR TITLE
[release-0.11] Disable the spinner if CLI is not attached to terminal (#1473)

### PR DESCRIPTION
**Pull request by joshrosso**
Note this cherry-pick had conflicts, and should be reviewed.

Signed-off-by: Lucheng Bao <luchengb@vmware.com>
(cherry picked from commit cae836d4bd5a14e58eb205e74c73002864672b80)
Signed-off-by: joshrosso <rossoj@vmware.com>

Original PR: 

* https://github.com/vmware-tanzu/tanzu-framework/pull/1473

### What this PR does / why we need it
Disable the spinner if CLI is not attached to terminal.
The previous forked branch `github.com/alonyb/spinner` has issue that causes spinner message being wiped out and redundant empty lines being printed out. Move the logic of checking terminal out to tanzu-framework

### Which issue(s) this PR fixes

Fixes # spinner message being wiped out and redundant empty lines being printed out

### Release note

```release-note
Bug fix: Fix the issue that spinner messages being wiped out and redundant empty lines being printed.
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @joshrosso: /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml

Tests can be triggered only by the trusted reviewers (users mentioned in CODEOWNERS file).

**Comment by blc1996** [comment]
We need to make sure the following cherry-picks happen in order
* https://github.com/vmware-tanzu/tanzu-framework/pull/1111
* https://github.com/vmware-tanzu/tanzu-framework/pull/1457
* https://github.com/vmware-tanzu/tanzu-framework/pull/1473

Thanks for taking care of it!

**Comment by alfredthenarwhal** [comment]
> @vijaykatam:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: 34a433c

Build failed! Build no: 1780

**Comment by navidshaikh** [comment]
>We need to make sure the following cherry-picks happen in order


Thanks @blc1996!

So,

- https://github.com/vmware-tanzu/tanzu-framework/pull/1977 goes first
- `Fix the race condition in spinner caused by active() check #1457` - is a no-diff against release-0.11 
- this PR https://github.com/vmware-tanzu/tanzu-framework/pull/1979 goes last

**Comment by navidshaikh** [comment]
@blc1996 : can you this a quick review please?

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: 04e5167

Tests failed! Build no: 1786

**Comment by alfredthenarwhal** [comment]
> @pallavijaini8075:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: 04e5167

Tests failed! Build no: 1790

**Comment by navidshaikh** [comment]
rebased 
/test install-vc7 --graph tkg-v1.5.3-zshippable.yaml

**Review by navidshaikh — APPROVED** [review]
lgtm!

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: 5885c08

Tests failed! Build no: 1792

**Comment by navidshaikh** [comment]
@pallavijaini8075 tested (build no 1790) the changes with AWS and Azure as there were issues with vc7 pipeline and added ok-to-test after tests yield success.

**Pull request merged**
