### PR TITLE
Bump Cobra from 1.5.0 to 1.6.1

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

This PR bumps to Cobra 1.6.1 which was recently released: https://github.com/spf13/cobra/releases/tag/v1.6.1
There is nothing really major in this new release, but it does have bug fixes and a couple of new features.  We should keep up to date.

### Describe testing done for PR

Let CI run

### CODE REVIEW

**Review by vuil — APPROVED** [review]
lgtm, assuming CI checks out

**Review by randomvariable — APPROVED** [review]

**Comment by marckhouzam** [comment]
This just needs the `ok-to-merge` label and it's good to go.

**Comment by randomvariable** [comment]
Let's get #3699  in first if we can

**Comment by marckhouzam** [comment]
> Let's get #3699 in first if we can

Sure, let's wait.  No particular hurry for the Cobra upgrade.

**Comment by marckhouzam** [comment]
I've updated the PR to move to Cobra 1.6.1 instead of 1.6.0 which was released yesterday

**Review by anujc25 — APPROVED** [review]
LGTM. Thanks for updating this.

**Comment by marckhouzam** [comment]
This PR is waiting for #3752 (which is replacing #3699) so we require yet another rebase from that PR.

**Comment by marckhouzam** [comment]
#3752 was replaced by #3772 which is now merged, so we can go ahead with this PR here.

**Review by anujc25 — APPROVED** [review]
LGTM. But need to make sure all CI pipelines are successful before we merge this.

**Comment by anujc25** [comment]
Looks like some unit tests are failing as part of [Main/Build CI](https://github.com/vmware-tanzu/tanzu-framework/actions/runs/3410714923/jobs/5689186031)
```
--- FAIL: TestKctrlInvoke (0.00s)
    --- FAIL: TestKctrlInvoke/Invoke (0.00s)
        --- FAIL: TestKctrlInvoke/Invoke/add_package_commands_from_kctrl (0.00s)
panic: Expected to find available commands section in spf13/cobra default usage template [recovered]
	panic: Expected to find available commands section in spf13/cobra default usage template
```

**Comment by marckhouzam** [comment]
> Looks like some unit tests are failing as part of [Main/Build CI](https://github.com/vmware-tanzu/tanzu-framework/actions/runs/3410714923/jobs/5689186031)
> 
> ```
> --- FAIL: TestKctrlInvoke (0.00s)
>     --- FAIL: TestKctrlInvoke/Invoke (0.00s)
>         --- FAIL: TestKctrlInvoke/Invoke/add_package_commands_from_kctrl (0.00s)
> panic: Expected to find available commands section in spf13/cobra default usage template [recovered]
> 	panic: Expected to find available commands section in spf13/cobra default usage template
> ```

Wow, thanks for finding this.  I will look into it.

**Comment by marckhouzam** [comment]
> Looks like some unit tests are failing as part of [Main/Build CI](https://github.com/vmware-tanzu/tanzu-framework/actions/runs/3410714923/jobs/5689186031)
> 
> ```
> --- FAIL: TestKctrlInvoke (0.00s)
>     --- FAIL: TestKctrlInvoke/Invoke (0.00s)
>         --- FAIL: TestKctrlInvoke/Invoke/add_package_commands_from_kctrl (0.00s)
> panic: Expected to find available commands section in spf13/cobra default usage template [recovered]
> 	panic: Expected to find available commands section in spf13/cobra default usage template
> ```

So Framework's `kctrl` imports `carvel-kapp-controller` which in turns uses `cppforlife` which needs to be modified to accept a recent Cobra change.  I will have to chase this down.

**Comment by marckhouzam** [comment]
I've made the CI pass by not bumping cobra for the `package` because it first needs `github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd` to be fixed once `github.com/cppforlife/cobrautil` is fixed.

However, I am concerned that another plugin may have a similar problem, but that it is not triggered by CI.

I have posted a PR to fix `github.com/cppforlife/cobrautil`: https://github.com/cppforlife/cobrautil/pull/8

**Pull request closed without merging**
