### PR TITLE
Send both IP families to vsphere-cpi

### PR DESCRIPTION
**Pull request by tylerschultz**
### What this PR does / why we need it

for dual-stack support

The CPI had previously not been able to accommodate receiving both IP families, causing undesired behavior.
Now that the CPI has been fixed and bumped, send both IP families.

### Which issue(s) this PR fixes

#616

### Describe testing done for PR

deployed updated package to test cluster, verified dualstack TKG_IP_FAMILY can be deployed

### Release note

```release-note
Nodes include secondary IP family when dual stack clusters are deployed on vSphere
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by mcwumbly — APPROVED** [review]
lgtm

**Comment by mcwumbly** [comment]
I wonder if this change should have a release note. I'm updating the description with the following:

```
Nodes include secondary IP family when dual stack clusters are deployed on vSphere
```

**Comment by mcwumbly** [comment]
@vmware-tanzu/tanzu-framework-reviewers any suggestions on who this should be assigned to or a CODEOWNER who can review?

**Comment by tylerschultz** [comment]
This PR needs to wait for an update to the vsphere-cpi before it should be merged. The vsphere-cpi has a validation preventing setting dualstack ipfamily configurations that needs to be updated.

**Review by vuil — APPROVED** [review]
lgtm, thanks! Let's keep the hold until the cpi dependency update is complete.

**Comment by mcwumbly** [comment]
The vsphere-cpi changes have now been merged so removing the `do-not-merge/hold` label. This should be ready to merge now.

**Pull request merged**
