### PR TITLE
Add logic to not to extract kube-vip manifest when kube-vip manifest is not presented in KCP, assume AVI

### PR DESCRIPTION
**Pull request by lubronzhan**
### What this PR does / why we need it
Currently, when avi is the control plane HA provider, the upgrade will faile
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @lubronzhan:  /test install-vc7
Commit: 81d993c

Tests passed! Build no: 4215

**Review by wjun — APPROVED** [review]
LGTM.

**Review by XudongLiuHarold — APPROVED** [review]
LGTM

**Comment by alfredthenarwhal** [comment]
Created cherry-pick PR

**Comment by navidshaikh** [comment]
> Created cherry-pick PR

this is incorrect, the cherry-pick notification should be fixed now: https://github.com/vmware-tanzu/tanzu-framework/pull/4428

**Pull request merged**
