### PR TITLE
Create a top-level directory for provider

### PR DESCRIPTION
**Pull request by Vandy-P**
Signed-off-by: Vandana Pathak <pathakv@sjc-ubu-eng-127.vmware.com>

### What this PR does / why we need it
Moving  provider  to top level directory 
### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
Build make test passing.

### Release note

```release-note

```

### CODE REVIEW

**Review by tenczar — APPROVED** [review]
LGTM. Let me just double check with the powers that be that moving this all the way to the top is exactly what they wanted. I do not want to have to revert this and try again. Also, let's make sure this gets merged as one commit to be able to back it out easily

**Review by ShashankGirish — APPROVED** [review]
LGTM.

**Review by sathyanarays — APPROVED** [review]

**Review by anujc25 — COMMENTED** [review]
Overall changes looks good.

However, we need proper explanation in the PR description on what changes has been done as part of the PR, upstream issues and release note etc.

Also commit message needs to be changed. currently it shows  as`[Signed-off-by: Vandana Pathak <pathakv@sjc-ubu-eng-127.vmware.com>]`.

Also, it would have been nice if we could have break the changes down into logical groups to ease the review process?

**Comment by Vandy-P** [comment]
Creating New PR from a branch of T/F repo
https://github.com/vmware-tanzu/tanzu-framework/pull/3243

**Pull request closed without merging**
