### PR TITLE
[release-0.11]: Add edition to tkg-metadata configmap

### PR DESCRIPTION
**Pull request by joshrosso**
### What this PR does / why we need it
Backport https://github.com/vmware-tanzu/tanzu-framework/pull/1949

This propogates the edition (tce vs tkg) to the tkg-metadata confimap.
This requirement came from a need for Tanzu Mission Control (TMC) to
be able to detect the type of workload cluster. However, this field
should propogate in both workload and management clusters.

### Which issue(s) this PR fixes

* Fixes: https://github.com/vmware-tanzu/community-edition/issues/3593

### Describe testing done for PR

1. Created a docker-based cluster with the edition set to `tce`.

    snapshot of `config.yaml`:

    ```yaml
    $ grep edition ~/.config/tanzu/config.yaml
        edition: tce
    ```

1. Query edition in configmap:

    ```yaml
    $ docker exec -it 634 kubectl --kubeconfig=/etc/kubernetes/admin.conf get cm -n tkg-system-public tkg-metadata -oyaml | grep -i edition
          edition: tce
    ```

### Release note

```release-note
tanzu edition now exposed in `tkg-metadata` configmap
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: 7ec2fb7

Tests passed! Build no: 1768

**Comment by alfredthenarwhal** [comment]
> @joshrosso: /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml

Tests can be triggered only by the trusted reviewers (users mentioned in CODEOWNERS file).

**Comment by alfredthenarwhal** [comment]
> @stmcginnis:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: a758312

Tests passed! Build no: 1781

**Comment by navidshaikh** [comment]
rebased

cc: @anujc25 @vuil this is ready to go

**Review by anujc25 — APPROVED** [review]

**Pull request merged**
