### PR TITLE
update ClusterAPI version to v1.0.1

### LINKED ISSUE #1152: upgrade ClusterAPI to v1.0.1
**Describe the feature request**
Upgrade Cluster API to v1.0.1 (latest version about to release in a few days). This release addresses some upgrade related bugs in Cluster API v1.0.0.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

### PR DESCRIPTION
**Pull request by ykakarap**
### What this PR does / why we need it

This PR update the ClusterAPI version to v1.0.1

### Which issue(s) this PR fixes

Fixes #1152

### Release note

```release-note
Bump ClusterAPI to v1.0.1
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.5.0-zshippable/381220738360694208/tkg-compatibility:v2

**Review by ankeesler — APPROVED** [review]
i'm kinda confused why the post-deploy job go.sum changed. my hunch is that it was leftover from a previous change and we forgot to do a `go mod tidy`, so i'll approve

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.5.0-zshippable/381631393991541939/tkg-compatibility:v2

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.5.0-zshippable/381929106058559551/tkg-compatibility:v2

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.6.0-zshippable/382815536272139094/tkg-compatibility:v2

**Comment by ykakarap** [comment]
//usebom:sandbox/v1.6.0-zshippable/383701932126003656/tkg-compatibility:v2

**Review by vuil — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
