### PR TITLE
Ensure legacy cluster upgrade does not overwrite kube-apiserver admission-control-config-file flag

### PR DESCRIPTION
**Pull request by chrischdi**
### What this PR does / why we need it

Fixes the legacy cluster upgrade to not overwrite an previously existing kube-apiserver flag `admission-control-config-file` in KCP.

Only affects Cluster upgrades to Kubernetes v1.24

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test upgrade-vc7
Commit: 6848a83

Tests passed! Build no: 3914

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test upgrade-vc7
Commit: 2f8ea3f

Tests passed! Build no: 3926

**Review by DanielXiao — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test upgrade-vc7 --test-params "CLUSTER_TYPE:legacy"
Commit: 2f8ea3f

Tests passed! Build no: 3971

**Comment by chrischdi** [comment]
@vmware-tanzu/tanzu-framework-lcm-reviewers would appreciate if someone could take a look at this to get this further :-)

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test upgrade-aws --test-params "CLUSTER_TYPE:legacy"
Commit: 2f8ea3f

Tests failed! Build no: 4013

**Comment by chrischdi** [comment]
> > @chrischdi:  /test upgrade-aws --test-params "CLUSTER_TYPE:legacy"
> > Commit: [2f8ea3f](https://github.com/vmware-tanzu/tanzu-framework/commit/2f8ea3f0069f1a124a05ceef4bc79eac1b94abb4)
> 
> Tests failed! Build no: 4013

Failure is unrelated to this change.

**Review by wjun — APPROVED** [review]

**Pull request merged**
