### PR TITLE
Enable configuration for net permissions

### PR DESCRIPTION
**Pull request by nikhilbarge**
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @nikhilbarge:  /test upgrade-vc7
Commit: 65618a8

Tests failed! Build no: 4132

**Comment by alfredthenarwhal** [comment]
> @nikhilbarge:  /test install-vc7
Commit: 65618a8

Tests failed! Build no: 4131

**Comment by nikhilbarge** [comment]
closed and new pr opened [4412](https://github.com/vmware-tanzu/tanzu-framework/pull/4412/)

**Pull request closed without merging**
