### PR TITLE
[release-0.11] Supress output of spinner if not connected to terminal (#1111)

### LINKED ISSUE #1066: Suppress sending ansi code if the output is not attached to TTY
**Bug description**

When you use tanzu cli in combination with `watch` it spits out a bunch of ansi control characters that aren't supported in that context.

To reproduce do something like this in a terminal:

```
watch tanzu package installed list -A
```

You'll get output that looks like this:

```
Every 2.0s: tanzu package installed list -A                                                                                           dellicioso: Thu Nov  4 13:32:11 2021

^[K | Retrieving installed packages... ^[K / Retrieving installed packages... ^[K - Retrieving installed packages... ^[K \ Retrieving installed packages... ^[K | Retrievi
ng installed packages... ^[K / Retrieving installed packages... ^[K - Retrieving installed packages... ^[K \ Retrieving installed packages... ^[K | Retrieving installed p
ackages... ^[K / Retrieving installed packages... ^[K - Retrieving installed packages... ^[K \ Retrieving installed packages... ^[K | Retrieving installed packages... ^[K
 / Retrieving installed packages... ^[K - Retrieving installed packages... ^[K \ Retrieving installed packages... ^[K | Retrieving installed packages... ^[K / Retrieving
installed packages... ^[K - Retrieving installed packages... ^[K \ Retrieving installed packages... ^[K | Retrieving installed packages... ^[K / Retrieving installed pack
ages... ^[K - Retrieving installed packages... ^[K \ Retrieving installed packages... ^[K | Retrieving installed packages... ^[K / Retrieving installed packages... ^[K -
Retrieving installed packages... ^[K \ Retrieving installed packages... ^[K | Retrieving installed packages... ^[K / Retrieving installed packages... ^[K - Retrieving ins
talled packages... ^[K \ Retrieving installed packages... ^[K | Retrieving installed packages... ^[K / Retrieving installed packages... ^[K - Retrieving installed package
s... ^[K \ Retrieving installed packages... ^[K
  ^[1mNAME                              ^[0m  ^[1mPACKAGE-NAME                                       ^[0m  ^[1mPACKAGE-VERSION^[0m  ^[1mSTATUS             ^[0m  ^[1mNAMES
PACE  ^[0m
  appliveview                         appliveview.tanzu.vmware.com                         0.3.0-build6     Reconcile succeeded  tap-install
  buildservice                        buildservice.tanzu.vmware.com                        1.3.1            Reconciling          tap-install
  cartographer                        cartographer.tanzu.vmware.com                        0.0.7            Reconcile succeeded  tap-install
  cnrs                                cnrs.tanzu.vmware.com                                1.0.3            Reconcile succeeded  tap-install
  conventions-controller              controller.conventions.apps.tanzu.vmware.com         0.4.2            Reconcile succeeded  tap-install
  developer-conventions               developer-conventions.tanzu.vmware.com               0.3.0-build.1    Reconcile succeeded  tap-install
  image-policy-webhook                image-policy-webhook.signing.run.tanzu.vmware.com    1.0.0-beta.1     Reconcile succeeded  tap-install
  ootb-supply-chain-basic             ootb-supply-chain-basic.tanzu.vmware.com             0.3.0-build.4    Reconcile succeeded  tap-install
  ootb-supply-chain-testing           ootb-supply-chain-testing.tanzu.vmware.com           0.3.0-build.4    Reconcile succeeded  tap-install
  ootb-supply-chain-testing-scanning  ootb-supply-chain-testing-scanning.tanzu.vmware.com  0.3.0-build.4    Reconcile succeeded  tap-install
  ootb-templates                      ootb-templates.tanzu.vmware.com                      0.3.0-build.4    Reconcile succeeded  tap-install
  service-bindings                    service-bindings.labs.vmware.com                     0.5.0            Reconcile succeeded  tap-install
  services-toolkit                    services-toolkit.tanzu.vmware.com                    0.4.0-rc.2       Reconcile succeeded  tap-install
  source-controller                   controller.source.apps.tanzu.vmware.com              0.1.2            Reconcile succeeded  tap-install
  spring-boot-conventions             spring-boot-conventions.tanzu.vmware.com             0.1.2            Reconcile succeeded  tap-install
  tap                                 tap.tanzu.vmware.com                                 0.3.0-build.6    Reconciling          tap-install
  tap-gui                             tap-gui.tanzu.vmware.com                             0.3.0-rc.4       Reconcile succeeded  tap-install
```

Notice the cruft at the beginning. 

This is a minor nuisance, but it would be good to fix it. (I.e. detect when the output isn't attached directly to a terminal and refrain in that case from sending ansi codes to do 'fancy' things that only a terminal understands).

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ *] CLI
- [ ] Docs
- [ ] IAM
- [* ] Installation
- [ *] Plugin
- [ ] Security
- [ ] Test and Release
- [ *] User Experience

**Expected behavior**

Suppress sending ansi code if the output is not attached to TTY.

**Version** (include the SHA if the version is not obvious)

```
$ tanzu version
version: v0.10.0
buildDate: 2021-11-03
sha: fd96bebe
```

```
$ tanzu plugin list
  NAME                LATEST VERSION  DESCRIPTION                                                        REPOSITORY  VERSION  STATUS     
  apps                                Applications on Kubernetes                                                     v0.2.0   installed  
  cluster             v0.10.0         Kubernetes cluster operations                                      core        v0.10.0  installed  
  kubernetes-release  v0.10.0         Kubernetes release operations                                      core        v0.10.0  installed  
  login               v0.10.0         Login to the platform                                              core        v0.10.0  installed  
  management-cluster  v0.10.0         Kubernetes management cluster operations                           core        v0.10.0  installed  
  package             v0.10.0         Tanzu package management                                           core        v0.10.0  installed  
  pinniped-auth       v0.10.0         Pinniped authentication operations (usually not directly invoked)  core        v0.10.0  installed  
  secret              v0.10.0         Tanzu secret management                                            core        v0.10.0  installed  

```

**Environment where the bug was observed (cloud, OS, etc)**

Ubuntu 18.04, bash terminal

### PR DESCRIPTION
**Pull request by joshrosso**
Signed-off-by: Lucheng Bao <luchengb@vmware.com>
(cherry picked from commit ab478bb2e4a9b2b802defc461d974b15df786c82)
Signed-off-by: joshrosso <rossoj@vmware.com>

Signed-off-by: Lucheng Bao <luchengb@vmware.com>

Original PR:

* https://github.com/vmware-tanzu/tanzu-framework/pull/1111

### What this PR does / why we need it

CLI spinner uses ANSI control code to do things like erase the current line. This control code will only be recognized by terminal.

Disable the spinner if the data is piped.

### Which issue(s) this PR fixes

Fixes #1066 #1016 

### Describe testing done for PR
test pipelines
Manual testing on local machine

### Release note

```release-note
None
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @joshrosso: /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml

Tests can be triggered only by the trusted reviewers (users mentioned in CODEOWNERS file).

**Comment by blc1996** [comment]
Hi @joshrosso , this cherry-pick MR doesn't fix the issue. The library used here happend to have another issue, and there are follow-up fix MRs https://github.com/vmware-tanzu/tanzu-framework/pull/1473/files.

**Comment by stmcginnis** [comment]
The follow on is being addressed in https://github.com/vmware-tanzu/tanzu-framework/pull/1979

**Comment by alfredthenarwhal** [comment]
> @stmcginnis:  /test install-vc7 --graph tkg-v1.5.3-zshippable.yaml
Commit: 898831e

Tests passed! Build no: 1782

**Review by anujc25 — APPROVED** [review]

**Pull request merged**
