### PR TITLE
Bump CAPA to v1.1.0

### LINKED ISSUE #1193: Upgrade CAPA to v1.1.0
Upgrade  CAPA to v1.1.0. This release has an updated controller runtime and cluster api release with some bug fixes.

### PR DESCRIPTION
**Pull request by sedefsavas**
### What this PR does / why we need it
This PR update the Cluster API Provider AWS version to v1.1.0.

Fixes https://github.com/vmware-tanzu/tanzu-framework/issues/1193

### Release note

```release-note
Bump CAPA to v1.1.0
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by sedefsavas** [comment]
@anujc25 @vuil 
Integration test failed due to CAPZ, which is not touched by this PR. What should I do?

**Comment by sedefsavas** [comment]
//usebom:sandbox/v1.6.0-zshippable/383760823778017711/tkg-compatibility:v2

**Comment by sedefsavas** [comment]
//usebom:sandbox/v1.6.0-zshippable/383829940069468718/tkg-compatibility:v2

**Comment by sedefsavas** [comment]
//usebom:sandbox/v1.6.0-zshippable/383931540859540783/tkg-compatibility:v2

**Comment by sedefsavas** [comment]
//usebom:sandbox/v1.6.0-zshippable/383947424286145198/tkg-compatibility:v2

**Comment by sedefsavas** [comment]
@vuil This PR is ready to be merged just waiting for the final signal from the tests. Just a heads up.

**Comment by vuil** [comment]
The clustergen outputs are generating a bunch of negative test cases becuase it is still attempting to use the previous provider version:

```
pkg/v1/providers/tests/clustergen/param_models/cluster_aws.model:_INFRA: "aws:v1.0.0"
pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model:_INFRA: "vsphere:v1.0.1", "aws:v1.0.0"
```

**Comment by sedefsavas** [comment]
Clustergen test fails to find templates:

`unable to get template: failed to read "cluster-template-definition-dev.yaml" from provider's repository "infrastructure-aws": failed to read file "/tmp/test_tkg_config_dir/providers/infrastructure-aws/v1.1.0/cluster-template-definition-dev.yaml" from local release v1.1.0: stat /tmp/test_tkg_config_dir/providers/infrastructure-aws/v1.1.0/cluster-template-definition-dev.yaml: no such file or directory`

They are there, any idea?

**Comment by vuil** [comment]
The template tests passed and seem too show the expected diffs. Where you are seeing the issue?

**Comment by sedefsavas** [comment]
In clustergen tests:
https://github.com/vmware-tanzu/tanzu-framework/pull/1209#issuecomment-984077470

**Comment by vuil** [comment]
Thanks, that is a known issue because we generated the same set of test cases to dry-run with two versions of the CLI. (and the older version is missing the new files), but the clustergen changes will still help with future PRs. 
@rajathagasthya has a PR to address the test failure on the first check, btw.

**Comment by sedefsavas** [comment]
Thanks @vuil, tests are passing now.

**Review by vuil — APPROVED** [review]
Thanks for the changes, and patience in working through the checks. 
LGTM.

**Pull request merged**
