### PR TITLE
Fix default indent

### PR DESCRIPTION
**Pull request by tenczar**
This change fixes a nesting issue for defaults in clusterclass
variables. The default was set on the variable and not the openAPISchema
for the variable. Affects aws, azure and vsphere

### Which issue(s) this PR fixes

Fixes # NA

### Release note

```release-note
None
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by saji-pivotal — COMMENTED** [review]
@tenczar The changes look good to me. Can you please update the PR description with the testing done for this?

**Comment by vuil** [comment]
@tenczar the https://storage.googleapis.com/tkg-clustergen/2420/20220520172657/clustergen.diff.txt diffs seems pretty useful to ascertain the effects of the change, please review and acknowledge the msg from the github-actions bot as it suggests.

**Review by vuil — APPROVED** [review]
lgtm

**Review by vuil — APPROVED** [review]
lgtm

**Pull request merged**
