### PR TITLE
[release-0.11] Load all credential helpers (#1816)

### PR DESCRIPTION
**Pull request by maralavi**
### What this PR does / why we need it

cherry-pick fix for OIDC auth issue (main branch PR https://github.com/vmware-tanzu/tanzu-framework/pull/1816) into release-0.11

Any place we load one of the k8s credential helpers, load them all.
Since we don't know what clusters users will use Tanzu with, we need to
support everything.

Signed-off-by: Scott Andrews <andrewssc@vmware.com>

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

Created TKG 1.5.3  cluster using the updated [buildinfo file](http://artifactory/artifactory/kscom-generic-local/TKG/channels/tkg-v1.5.3-zshippable-stable/tkg-v1.5.3-zshippable.buildinfo.yaml)
Validated all Package/Secret plugin commands are working correctly by trying to install an authenticated package repository and testing all operations for both plugins

### Release note

```release-note
Fix for OIDC auth issue: Load all kubernetes credential helpers
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by maralavi** [comment]
@vijaykatam the ```go.mod``` changes in the [PR to main](https://github.com/vmware-tanzu/tanzu-framework/pull/1816 ) would get dropped with ```go mod tidy```. Because of that, this PR only has some new entries in ```go.sum``` but indirect entries which were introduced in the [PR to main](https://github.com/vmware-tanzu/tanzu-framework/pull/1816) are removed

**Comment by vijaykatam** [comment]
Change looks good. Please add release note and rebase with latest from release-0.11

**Comment by maralavi** [comment]
> Change looks good. Please add release note and rebase with latest from release-0.11

Just rebase with latest changes in release-0.11 and added the release note

**Review by anujc25 — APPROVED** [review]

**Comment by navidshaikh** [comment]
Updated release notes.

**Pull request merged**
