### PR TITLE
Allowing spread of Windows MD across zones

### LINKED ISSUE #4114: Wrong Windows MD workers replicas on prod plan
**Bug description**
Windows clusters using prod creates 3 MD for vSphere (one for each failure zone) and always set WORKER_MACHINE_COUNT in the first MD replicas instead of spreading them out.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- (x) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
To have the workers spread across MDs as Linux, the Cluster template is already fixed on 
https://github.com/vmware-tanzu/tanzu-framework/pull/3893

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by knabben**
### What this PR does / why we need it
Allow distribution of workers on different MDs for Windows clusters.

### Which issue(s) this PR fixes

Fixes #4114

### Release note

```release-note

```

### Additional information

Tests were manually executed when creating the cluster

```
    workers:
      machineDeployments:
      - class: tkg-worker-windows
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=windows
        name: md-0
        replicas: 1
      - class: tkg-worker-windows
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=windows
        name: md-1
        replicas: 1
      - class: tkg-worker-windows
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=windows
        name: md-2
        replicas: 1
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-vc7
Commit: 0f33efb

Build failed! Build no: 3500

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-vc7
Commit: 0f33efb

Tests failed! Build no: 3502

**Review by DanielXiao — APPROVED** [review]

**Review by tenczar — APPROVED** [review]
LGTM

**Comment by alfredthenarwhal** [comment]
> @knabben:  /test install-vc7
Commit: a4dc4ab

Tests failed! Build no: 3546

**Review by wjun — APPROVED** [review]
LGTM

**Pull request merged**
