### PR TITLE
clusterclient: Add capi experimental to scheme to allow tanzu get cluster to work

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

### Which issue(s) this PR fixes

Resolves issue when running `tanzu cluster get` with the error:

`Error: no kind is registered for the type v1beta1.MachinePoolList in scheme "pkg/runtime/scheme.go:100"` 

### Describe testing done for PR
Seems we need a full e2e downstream, hence the /test install-vc7

### Release note

```release-note

```

### CODE REVIEW

**Review by shyaamsn — APPROVED** [review]

**Review by shyaamsn — COMMENTED** [review]
Do we need this change even if any of the CRs from clusterapiv1beta1exp are not used in addons-controller ?

**Comment by randomvariable** [comment]
> Do we need this change even if any of the CRs from clusterapiv1beta1exp are not used in addons-controller ?

addons controller was a red herring, the problem was in the clusterclient it seems

**Comment by randomvariable** [comment]
It is EOD for me now, so hopefully @jayunit100 can find someone to delegate to. cc @tenczar

**Comment by randomvariable** [comment]
This is only the test file though, need to find where to add it...

**Comment by alfredthenarwhal** [comment]
Tests passed! Build no: 2918

**Comment by jeffwubj** [comment]
in my current main build, tanzu mc get is broken
```
jeffwu@ip-172-31-15-185 ~/g/s/g/v/t/c/c/p/managementcluster (main) [1]> tanzu mc get
Error: no kind is registered for the type v1beta1.MachinePoolList in scheme "pkg/runtime/scheme.go:100"
```
maybe need to add these to management-cluster plugin ?

**Review by wjun — APPROVED** [review]

**Comment by jayunit100** [comment]
thanks for the quick turnaround on this folks

**Pull request merged**
