### PR TITLE
Overwrite existing TKRs when installing TKRs from TKR packages

### PR DESCRIPTION
**Pull request by imikushin**
### What this PR does / why we need it

Without this, TKRs that have been installed to TKG v1.6 are going to only be usable in legacy mode: they will lack information about OS images and bootstrap packages.

### Which issue(s) this PR fixes

N/A

### Describe testing done for PR

Modified a unit test to reproduce the erroneous behavior.

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by hongtaiwang** [comment]
lgtm

**Comment by randomvariable** [comment]
Is this going to overwrite customised OSImages, ala Oracle?

**Comment by imikushin** [comment]
> Is this going to overwrite customised OSImages, ala Oracle?

If they have the same names, yes.

**Comment by imikushin** [comment]
Just had an offline discussion with @randomvariable:
Excluding OSImage objects from overwriting, as a quick fix to keep Oracle support working,

**Review by prkalle — APPROVED** [review]
LGTM. Thanks @imikushin

**Pull request merged**
