### PR TITLE
Setup proxy configuration to infrastructure controllers

### PR DESCRIPTION
**Pull request by saimanoj01**
### What this PR does / why we need it
Configure proxy settings for the CAP* infrastructure-provider controllers. It is really important for customer working with air-gapped scenarios.

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
Setup a squid proxy on an Azure and verified creating a management cluster using the proxy.

### Release note

```release-note
Fix bug to enable setting up proxy for cap* infrastructure controllers. 
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by tenczar — APPROVED** [review]
LGTM. Do we have a reference to the original commit/PR for these changes? If they were pre tanzu-framework then no big deal.

**Review by saji-pivotal — APPROVED** [review]

**Review by anujc25 — APPROVED** [review]
LGTM

**Comment by anujc25** [comment]
@saimanoj01 please add the release note to mention that this bug is fixed.

**Comment by saimanoj01** [comment]
> Do we have a reference to the original commit/PR for these changes? If they were pre tanzu-framework then no big deal.
 @tenczar It was introduced when we were on `core` - https://github.com/vmware-tanzu-private/core/pull/707/files

**Pull request merged**
