### PR TITLE
Set improved pod security configuration for cert-manager in MC to comply with restricted policy

### PR DESCRIPTION
**Pull request by chrischdi**
### What this PR does / why we need it

Adjusts the cert-manager manifest which is only used for management clusters to comply with the pod security standard's `restricted` policy.

This is a one-time change, and won't be needed anymore when bumping to cert-manager v1.10+, because the upstream provided yamls also fix that.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test install-vc7
Commit: fcb3fa2

Tests failed! Build no: 4354

**Comment by chrischdi** [comment]
> > @chrischdi:  /test install-vc7
> > Commit: [fcb3fa2](https://github.com/vmware-tanzu/tanzu-framework/commit/fcb3fa2f06391b0bc57ecc22ceac35fce85df9cd)
> 
> Tests failed! Build no: 4354

failed due to build failure, unrelated to MR

**Comment by chrischdi** [comment]
blocked by #4458

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test install-vc7
Commit: fcb3fa2

Tests failed! Build no: 4367

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test install-vc7
Commit: 0389d01

Tests passed! Build no: 4390

**Review by sathyanarays — APPROVED** [review]

**Review by imikushin — APPROVED** [review]
LGTM

**Comment by chrischdi** [comment]
/hold to check if this is superseded by https://github.com/vmware-tanzu/tanzu-framework/pull/4490

(checking is WIP by me)

**Comment by chrischdi** [comment]
This got supersedded by https://github.com/vmware-tanzu/tanzu-framework/pull/4490

**Pull request closed without merging**
