### PR TITLE
[Part 1] Extract TKG client lib to top level package

### LINKED ISSUE #3241: Extract TKG client lib to top level package
**Describe the feature request**
The core functionality of the TKG client lib supports operations used by the cluster and management cluster plugin. To support reuse of logic in this client lib, move it to a separate top level package with its own go module.

**Describe alternative(s) you've considered**

**Affected product area (please put an X in all that apply)**

- (x) APIs
- (x) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- (x) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Additional context**

### PR DESCRIPTION
**Pull request by sathyanarays**
#### Moving pkg/v1/tkg as a top level go module

    Signed-off-by: Sathyanarayanan Saravanamuthu <sathyanarays@vmware.com>
    Signed-off-by: Vandana Pathak <pathakv@vmware.com>
    
    Co-authored-by: Sathyanarayanan Saravanamuthu <sathyanarays@vmware.com>
    Co-authored-by: Vandana Pathak <pathakv@vmware.com>

### What this PR does / why we need it
The core functionality of the TKG client lib supports operations used by the cluster and management cluster plugin. To support reuse of logic in this client lib, move it to a separate top level package with its own go module.

### Which issue(s) this PR fixes

Fixes #3241 

### Change details
Moved the following directories from `pkg/v1/tkg` to `tkg` module:
- avi
- aws
- azure
- buildinfo
- constants
- docker
- features
- kind
- ldap
- log
- region
- utils
- yamlprocessor

### References
- [PR 3245](https://github.com/vmware-tanzu/tanzu-framework/pull/3245). Closed because it had 1500+ files changed and suggested to split into multiple PRs

### CODE REVIEW

**Comment by anujc25** [comment]
Changes LGTM.

Can you please add description of all the packages moved as part of this PR in the PR description?

**Comment by sathyanarays** [comment]
> Changes LGTM.
> 
> Can you please add description of all the packages moved as part of this PR in the PR description?

@anujc25 done

**Comment by danniel1205** [comment]
I have reviewed the Pinniped part, it LGTM.

**Comment by danniel1205** [comment]
Addons part LGTM too. Thanks for the change.

**Comment by vuil** [comment]
lgtm, this change needs a rebase, and the resulting commits can use some squashing.

**Review by anujc25 — APPROVED** [review]
LGTM

**Pull request merged**
