### PR TITLE
Set improved pod security configuration for CAPI components in MC to comply with restricted policy

### PR DESCRIPTION
**Pull request by chrischdi**
### What this PR does / why we need it

Adjusts the CAPI and CAPI Provider manifests which are used for management clusters to comply with the pod security standard's restricted policy.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test install-aws
Commit: f482eef

Tests failed! Build no: 4355

**Comment by chrischdi** [comment]
blocked by #4458

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test install-aws
Commit: 86a3bc4

Tests passed! Build no: 4389

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test install-vc7
Commit: 1bb3ede

Tests passed! Build no: 4394

**Review by wjun — APPROVED** [review]
LGTM

**Comment by chrischdi** [comment]
@wjun , is this ok if I hit merge then?

Pipelines I did run to do additional test were all green:
* install aws
* install vc7
* install azure
* upgrade aws

**Comment by wjun** [comment]
@chrischdi Do the install * tests better to pass in k8s 1.25 or it is ok to pass in k8s 1.24? I noticed the bom is refreshed to k8s 1.25 recently after your tests. If it does not matter, please go ahead to merge it. Otherwise, please hold as we noticed aws upgrade related tests failed recently.

**Comment by chrischdi** [comment]
> @chrischdi Do the install * tests better to pass in k8s 1.25 or it is ok to pass in k8s 1.24? I noticed the bom is refreshed to k8s 1.25 recently after your tests. If it does not matter, please go ahead to merge it. Otherwise, please hold as we noticed all upgrade related tests failed recently.

The change is unrelated to v1.25, however I will make sure to verify that to be 100% sure 👍

**Comment by alfredthenarwhal** [comment]
> @chrischdi:  /test install-aws
Commit: 1bb3ede

Tests failed! Build no: 4412

**Comment by chrischdi** [comment]
> > @chrischdi:  /test install-aws
> > Commit: [1bb3ede](https://github.com/vmware-tanzu/tanzu-framework/commit/1bb3ede3cdf580a45fc880c1ec63c4bd53419430)
> 
> Tests failed! Build no: 4412

build flake

**Comment by chrischdi** [comment]
reverified successfully on v1.25 for aws, azure and vc7, thus merging

**Pull request merged**
