### PR TITLE
CLI: Add target separation

### LINKED ISSUE #2201: Explicit context type or target in command invocation in the Tanzu CLI
**Describe the feature request**
Depends on #2200.

Once we have the various context types defined, we need to group the plugins by the context types to overcome conflicts in plugin names. For example, both a TKG/TCE management cluster and TMC support `cluster` plugins. This can create easily confusion to new users who are referring to some form of documentation because the underlying APIs are completely different and so are the capabilities. To avoid this kind of confusion, we need to include the context type or target in the command invocation.

With this change, the commands would look like below.
1. Set context to TKG management cluster
```
~ tanzu context use tkg-aws
```
```
~ tanzu -h
Tanzu CLI

Usage:
  tanzu [command]

Available command groups:

  Run
    cluster                 Kubernetes cluster operations
    feature                 Operate on features and featuregates
    kubernetes-release      Kubernetes release operations
    management-cluster      Kubernetes management cluster operations
    package                 Tanzu package management
    secret                  Tanzu secret management
    telemetry               configure cluster-wide settings for vmware tanzu telemetry

  System
    completion              Output shell completion code
    config                  Configuration for the CLI
    context                 Configure and manage contexts for the Tanzu CLI
    init                    Initialize the CLI
    login                   Login to the platform
    plugin                  Manage CLI plugins
    update                  Update the CLI
    version                 Version information

  Target
    kubernetes              Tanzu CLI plugins that target a Kubernetes cluster
    mission-control         Tanzu CLI plugins that target a Tanzu Mission Control endpoint


Flags:
  -h, --help   help for tanzu

Use "tanzu [command] --help" for more information about a command.

Logged in to tkg-aws
```
```
~ tanzu kubernetes -h
Tanzu CLI plugins that target a Kubernetes cluster

Usage:
  tanzu kubernetes [command]

Available command groups:

  Run
    cluster                 Kubernetes cluster operations
    feature                 Operate on features and featuregates
    kubernetes-release      Kubernetes release operations
    management-cluster      Kubernetes management cluster operations
    package                 Tanzu package management
    secret                  Tanzu secret management
    telemetry               configure cluster-wide settings for vmware tanzu telemetry


Flags:
  -h, --help   help for kubernetes

Use "tanzu kubernetes [command] --help" for more information about a command.

Logged in to tkg-aws
```
2. Set context to a TMC demo endpoint
```
~ tanzu context use tmc-demo
```
```
~ tanzu -h
Tanzu CLI

Usage:
  tanzu [command]

Available command groups:

  Manage
    cluster                 TMC cluster operations
    management-cluster      TMC management cluster operations

  Run
    package                 Tanzu package management
    secret                  Tanzu secret management
    telemetry               configure cluster-wide settings for vmware tanzu telemetry

  System
    completion              Output shell completion code
    config                  Configuration for the CLI
    context                 Configure and manage contexts for the Tanzu CLI
    init                    Initialize the CLI
    login                   Login to the platform
    plugin                  Manage CLI plugins
    update                  Update the CLI
    version                 Version information

  Target
    kubernetes              Tanzu CLI plugins that target a Kubernetes cluster
    mission-control         Tanzu CLI plugins that target a Tanzu Mission Control endpoint


Flags:
  -h, --help   help for tanzu

Use "tanzu [command] --help" for more information about a command.

Logged in to tmc-demo
```
```
~ tanzu mission-control -h
Tanzu CLI plugins that target a Tanzu Mission Control endpoint
Usage:
  tanzu kubernetes [command]

Available command groups:

  Manage
    cluster                 TMC cluster operations
    management-cluster      TMC management cluster operations


Flags:
  -h, --help   help for kubernetes

Use "tanzu kubernetes [command] --help" for more information about a command.

Logged in to tmc-demo
```

**Describe alternatives you've considered**
1. Changing the names of the plugins was considered to maintain uniqueness. But that seems to degrade the user experience. Also, it is hard to control all the available list of plugins in one place given the number of products involved.

**Affected product area (please put an X in all that apply)**
- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

### PR DESCRIPTION
**Pull request by giri-varma**
### What this PR does / why we need it

1. Currently, most stand-alone plugins are specific to the k8s context.
Hence, adding the context type to discovery source and grouping the
stand-alone plugins by context type. Only the stand-alone plugins
that are associated with a context type show up under the type.

2. Group contextual plugins by context type
Added kubernetes and TMC commands under root which further contain
plugins specific to those contexts. The plugins also show up under
root to maintain backwards compatibility.

### Which issue(s) this PR fixes
Fixes #2201

### Describe testing done for PR
Added unit tests for the config changes. Tested the `tanzu` targets  manually with the following steps:
1. Download an older version of the Tanzu CLI (`v0.21.0`)
2. Login with a management cluster `tanzu login`
3. Get management cluster `tanzu management-cluster get` & list clusters `tanzu cluster list` to ensure that the plugins are working
4. Upgrade to the new CLI with context command `make install-cli` and list the contexts `tanzu context list` to ensure the new CLI translates servers to contexts
5. Run `tanzu init` to update the new catalog fields
6. Get management cluster `tanzu management-cluster get` & list clusters `tanzu cluster list` to ensure that the existing invocations are still working
7. Get management cluster `tanzu kubernetes management-cluster get` & list clusters `tanzu kubernetes cluster list` to ensure that the new invocations are working

### Release note
```release-note
Currently, all CLI plugins are specific to the Kubernetes context. As more services like TMC add plugins, there is some room for confusion as there is name collision between the plugins. To make the user experience very explicit, we are adding the target to the command invocation.

With this change, the Tanzu CLI supports two targets (context types): `kubernetes`, `mission-control`. This is currently backwards compatible, i.e., the plugins are still available at the root level. In addition to that, we have all the contextual plugins grouped under their corresponding targets.

Note: This is currently behind a feature flag. To enable the flag please run tanzu config set features.global.context-target true and then run `tanzu init` once after the upgrade.

Please find some examples below:

1. TKG workload cluster plugin:
# Without target grouping (a TKG management cluster is set as the current active server)
`~ tanzu cluster`

# With target grouping
`~ tanzu kubernetes cluster`

2. TMC workload cluster plugin:
# Without target grouping (a TMC server is set as the current active server)
`~ tanzu cluster`

# With target grouping
`~ tanzu mission-control cluster`
```

### PR Checklist
- [x] Squash the commits into one or a small number of logical commits
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by vuil** [comment]
Thanks for the changes @giri-varma. I am generally fine with the changes, as long as the existing invocation behavior continues to be supported, and that we continue to iterate on how to provide backward compatibility to the non target-prefixed invocation style. 

On a related note:
The release notes section is probably not a place to include too much details, but as written it is not clear what one is supposed to expect when some of the commands are being run. e.g.

```
2. TMC workload cluster plugin:
# Without target grouping (a TMC server is set as the current active server)
`~ tanzu cluster`
```
Is this supposed to suggest that `tanzu cluster` will only show TMC-related commands? 
It might be good to include the output for reference, (either in the PR description or even better, the issue 2201) so other reviewers can get the nuance of how the UX changes or remains unchanged.

**Comment by vuil** [comment]
More on continuing to provide backward compatibility for the non-target prefixed (`tanzu commandgroup command...` instead of  `tanzu target commandgroup command...`)  invocation style:

It feels unsatifactory that the non-target style only applies to the k8s target (so as to retain compatibilty for all tanzu known plugins atm). I feel quite strongly that even with the introduction of using target to disambiguate among command groups of the same name, that we should continue to support the shortened style for commands at all target levels.

What looks to be making the latter difficult is that we do not have a concept of an "active" context (instead what we have today is a context assigned to each target level). It feels like a useful and fairly logical extension to record the last context used (not different from how kubeconfig context behaves). What that achieves besides being exact about what tanzu context the CLI is connecting to, is also at what target level the cli is targeting at any moment. Thus most of the time, tanzu commands not specific a target can imply the use of the target level of the active context.

**Comment by giri-varma** [comment]
@vuil Thank you for reviewing in detail! I have updated the description of the related issue as suggested.

> It feels unsatisfactory that the non-target style only applies to the k8s target (so as to retain compatibility for all tanzu known plugins atm). I feel quite strongly that even with the introduction of using target to disambiguate among command groups of the same name, that we should continue to support the shortened style for commands at all target levels.

I can see your point. I added a minor fix yesterday for TMC commands also to work without the target. The actual issue is for k8s targets that are not management clusters since they are not backwards comparible.

But I am also not sure if this non-targets UX has been agreed upon. If you don't mind, can you please create a new issue for the request to track it separately?

**Comment by vuil** [comment]
> But I am also not sure if this non-targets UX has been agreed upon. If you don't mind, can you please create a new issue for the request to track it separately?
Yeah, I don't think the decision need to block the change. Let's get this in and iterate on the non-target UX. 
I will file an issue to solicit some discussion on it.

**Review by vuil — APPROVED** [review]
Thanks for the patience and updating the PR.
Changes lgtm.

**Pull request merged**
