### PR TITLE
Default deploy-in-cluster-ipam-provider to true

### PR DESCRIPTION
**Pull request by flawedmatrix**
### What this PR does / why we need it
Enables the deploy in-cluster ipam provider feature flag by default and remove the beta suffix.

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

Deployed a management cluster locally and see the `caip-in-cluster-controller-manager` was deployed successfully and by default.

### Release note

```release-note
The `features.management-cluster.deploy-in-cluster-ipam-provider` feature flag is now enabled by default.
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @flawedmatrix:  /test install-vc7
Commit: 1e96e1e

Build failed! Build no: 3571

**Comment by alfredthenarwhal** [comment]
> @christianang:  /test install-vc7
Commit: 1e96e1e

Build failed! Build no: 3586

**Review by christianang — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
> @christianang:  /test install-vc7
Commit: c3dc0f4

Tests failed! Build no: 3591

**Review by imikushin — APPROVED** [review]
LGTM

**Pull request merged**
