### PR TITLE
Fix status slashing by PatchSet

### PR DESCRIPTION
**Pull request by imikushin**
### What this PR does / why we need it

Fix PatchSet slashing status changes leading to clearing of TKR
status conditions (as PatchSet is used by all TKR controllers).

### Which issue(s) this PR fixes

N/A

### Describe testing done for PR

Added unit tests illustrating the issue and failing w/o the fix in this change.

### Release note

```release-note
NONE
```

### PR Checklist

- [X] Squash the commits into one or a small number of logical commits
      
- [X] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [X] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by prkalle — APPROVED** [review]
LGTM. Thanks!

**Review by vuil — APPROVED** [review]
lgtm, thanks!

**Comment by alfredthenarwhal** [comment]
> @imikushin:  /test install-vc7
Commit: 62333a6

Tests failed! Build no: 2131

**Comment by navidshaikh** [comment]
the PR-branch should exists to trigger the build and tests, please restore the branch and re-trigger

**Pull request merged**
