### PR TITLE
Add codeowners for cmd/cli/plugin/package/kctrl

### PR DESCRIPTION
**Pull request by praveenrewar**
### What this PR does / why we need it
Add codeowners for cmd/cli/plugin/package/kctrl

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note
NONE
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by praveenrewar** [comment]
@vijaykatam One of the checks is failing and I feel that it's not related to the change that I have made. Should I go ahead and merge the PR?

**Comment by vijaykatam** [comment]
@praveenrewar could you retrigger the check. I have asked @adduarte to take a look at the test flakes.

**Comment by praveenrewar** [comment]
@rajathagasthya @vijaykatam Thanks. I have rebased with main.

**Comment by adduarte** [comment]
This needs to be rebased. The last failure is around parts of the code that have significant changed in main.

**Comment by adduarte** [comment]
:

> @rajathagasthya @vijaykatam Thanks. I have rebased with main.

yes. The failure of previous test  where around code that had significant differences with main branch.

**Pull request merged**
