### PR TITLE
Update from mirror.gcr.io to dockerhub

### PR DESCRIPTION
**Pull request by vijaykatam**
The mirror images in gcr go away after a while causing
build issues upstream and downstream. With dockerhub we
will run into ratelimiting but there is no other reasonable
alternative currently that we use with confidence.

Signed-off-by: Vijay Katam <vkatam@vmware.com>

### What this PR does / why we need it
mirror.gcr.io images are going away after a while causing build issues upstream and downstream

### Describe testing done for PR
Build one of the images.

### Release note

```release-note

```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by blc1996 — APPROVED** [review]
LGTM

**Review by yharish991 — APPROVED** [review]

**Review by ankeesler — COMMENTED** [review]
q: are we worried about downstream projects (e.g., TKG) starting to fail to build because they get rate limited when trying to build some of these images? might downstream build scripts might need to get updated to provide their own `BUILDER_BASE_IMAGE` when building these images?

**Comment by vijaykatam** [comment]
> might downstream build scripts might need to get updated to provide their own BUILDER_BASE_IMAGE when building these image
Yes, downstream build script is providing a harbor proxy cache image. `harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang:1.17`

**Review by ankeesler — APPROVED** [review]
ack, will follow up on downstream build discussion elsewhere

**Review by danniel1205 — APPROVED** [review]
LGTM

**Pull request merged**
