### PR TITLE
Update cobra to support plugin flag completion

### PR DESCRIPTION
**Pull request by scothis**
### What this PR does / why we need it

Updates cobra to a version that includes https://github.com/spf13/cobra/pull/1161 which
fixes an issue where completion options are not offered for plugin
flags.

Without this fix, the completion handler inside cobra is interpreted as returning flags for the command hosting the plugin. With this fix, when flag parsing is disabled for a commend, the custom completion hook is invoked, which the Tanzu CLI uses to collect completion info from plugins.

### Describe testing done for PR

I used the special hook provided by cobra that is used by shell completions to compare the suggestions with and without this PR.

```sh
tanzu __complete package install -
```
Without this PR (plugin flag completions are not available):

```sh
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```

With this PR (plugin flag completions are available):

```sh
--package-name  Name of the package to be installed
-p      Name of the package to be installed
--version       Version of the package to be installed
-v      Version of the package to be installed
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```

### Release note
```release-note
Plugins using native shell completion will now offer suggestions for flag names
```

### PR Checklist

- [X] Squash the commits into one or a small number of logical commits
- [X] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [X] Ensure PR contains terms all contributors can understand and links all contributors can access

#### Special notes for your reviewer

There is no tagged version of cobra that contains this patch, this commit is the HEAD of the master branch. We can switch back to tagged releases once there is a new release.

cc @jpmcb (who helped land the upstream PR)

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
I'm currently working on cutting a cobra release for v1.2.2

I propose we wait for a release instead of pinning to an arbitrary sha.

**Comment by scothis** [comment]
@jpmcb I can update after cobra releases or if someone else beats me to it we can close this PR. Either way, I verified that the Tanzu CLI completion issue is fixed by updating cobra.

**Comment by jpmcb** [comment]
>  I verified that the Tanzu CLI completion issue is fixed by updating cobra.

Awesome!! Very glad this fix worked for you :D 

I'll see how pushing through a release goes (hopefully by this week). If we need this feature to be in a `tanzu-framework` release, then we can have this go in intermittently before I get a release out

**Comment by jpmcb** [comment]
v1.3.0 has been cut! https://github.com/spf13/cobra/releases/tag/v1.3.0

Let me know if y'all need any support on this one!!

**Comment by scothis** [comment]
Rebased on main and updated cobra to 1.3.0

**Comment by scothis** [comment]
Rebased again

**Comment by miclettej** [comment]
@giri-varma PTAL, thanks!

**Review by jpmcb — APPROVED** [review]
From the cobra perspective, yes this is fine!

**Review by giri-varma — APPROVED** [review]

**Review by danniel1205 — APPROVED** [review]

**Pull request merged**
