### PR TITLE
Add ako and akoo composite packages

### PR DESCRIPTION
**Pull request by chenlin07**
### What this PR does / why we need it
add ako and akoo composite packages
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by lubronzhan** [comment]
Could you fix the failure in the test 
```
./hack/verify-dirty.sh
#############################
Verify uncommitted files...
#############################

The following files are uncommitted. Please commit them or add them to .gitignore:
- tkg/managementcomponents/helper.go

Diff:
diff --git a/tkg/managementcomponents/helper.go b/tkg/managementcomponents/helper.go
index e69320f6..002edcc3 100644
--- a/tkg/managementcomponents/helper.go
+++ b/tkg/managementcomponents/helper.go
@@ -8,13 +8,14 @@ import (
 	"encoding/base64"
 	"encoding/json"
 	"fmt"
-	"github.com/aunum/log"
-	"gopkg.in/yaml.v3"
 	"os"
 	"path/filepath"
 	"reflect"
 	"time"
 
+	"github.com/aunum/log"
+	"gopkg.in/yaml.v3"
+
 	"github.com/pkg/errors"
 
 	"github.com/vmware-tanzu/tanzu-framework/tkg/constants"
make: *** [Makefile:615: verify] Error 1
Error: Process completed with exit code 2.
```

**Comment by XudongLiuHarold** [comment]
hold until we solve the hardcode image path for akoo/ako issue.

**Comment by chenlin07** [comment]
Please refer to updated pr https://github.com/vmware-tanzu/tanzu-framework/pull/3919

**Pull request closed without merging**
