### PR TITLE
Remove cgroupfs cgroupdriver for capd on Kubernetes >= v1.24

### PR DESCRIPTION
**Pull request by chrischdi**
### What this PR does / why we need it

Fixes the CAPD integration tests which fail to create v1.24 clusters because the templates always set the cgroup driver to `cgroupfs`.
Kind images >= v1.24 only support the `systemd` cgroup driver.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Review by danniel1205 — APPROVED** [review]
lgtm, thanks for the fix.

**Comment by chrischdi** [comment]
This PR may replaced by #3933

**Comment by vuil** [comment]
@chrischdi thanks for your changes. I have rebased and merged it in #3933.

**Comment by chrischdi** [comment]
Closing because the relevant bits got merged via https://github.com/vmware-tanzu/tanzu-framework/pull/3933

**Pull request closed without merging**
