### PR TITLE
Sync remaining changes from package-based-lcm branch

### LINKED ISSUE #2589: Add `core-management-plugins-package` as part of TKG meta package
**Bug description**

When creating management-cluster using `package-based-lcm` feature flag enabled, context-scoped CLIPlugin resources are not getting deployed on the management-cluster.

So, when using official building, `tanzu plugin sync` might not be able to find context-scoped plugins. 

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
CLIPlugin should be available 

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### LINKED ISSUE #2597: Install additional-compatible-tkr related config map when creating/upgrading management-cluster
**Describe the feature request**

In conjunction to #2592, when creating management-cluster with `package-based-lcm` feature-flag enabled, we need to create a config map in the bootstrap as well and management-cluster to mark a specific TKR compatible that will be used for management-cluster creation and upgrade.

For this, we can create this ConfigMap as part of TKG composite package deployment and update the configMap during the management-package upgrade when upgrading the management-cluster to newer version.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tkr-metadata
  namespace: tkg-system
  labels:
    run.tanzu.vmware.com/additional-compatible-tkrs: ""
data:
  tkrVersions: |
    - v1.23.6+vmware.1-tkg.1
```

The version of the TKR to specify here will be determined from the default BoM file and will be passed as a dataValue to the TKG composite package.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

### PR DESCRIPTION
**Pull request by vuil**
### What this PR does / why we need it
This PR introduces the remaining set of changes from the `package-based-lcm branch`
Includes
- installing core-management-plugins-package as part of TKG composite package
- CCluster.yaml config validation
- CC-side fixes
- Conversion of user provided values into correct types during CC package installationo
- Introduce support for a compatible-tkr config map to preload a bootstrap cluster for MC creation

### Which issue(s) this PR fixes

Fixes #2597, 
Fixes #2589, 
Related to #2592

### Describe testing done for PR

UT ran on individual commits.
Will verify via CI pipelines and triggered downstream tests.

### Release note

```release-note

```

### PR Checklist

- x Squash the commits into one or a small number of logical commits
      
- x Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- x Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by anujc25 — APPROVED** [review]
Looks good

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2218

**Comment by alfredthenarwhal** [comment]
Tests passed! Build no: 2219

**Pull request merged**
