### PR TITLE
Enable feature-flag for `context-target` by default

### LINKED ISSUE #3653: Turn on context and target functionality
**Describe the feature request**

This is a follow up to enable by default the context and target functionality introduced in 

https://github.com/vmware-tanzu/tanzu-framework/pull/2202
https://github.com/vmware-tanzu/tanzu-framework/issues/2201

Said functionality had been behind a CLI feature flag global.features.context-target; the eliminate the use of said flag and make the functionality standard in future Tanzu CLI.

**Describe alternative(s) you've considered**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- (x) User Experience
- ( ) Developer Experience

**Additional context**

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it

- This PR enables the Context/Target feature-flag by default.

- This change requires rename of the feature-flag to `context-target-v2` to make sure default value gets update in the user's `config.yaml` if `context-target` feature-flag already exists. 
    - This is required because if the feature-flag already exists in `config.yaml` than current logic does not change the value.

### Which issue(s) this PR fixes

Fixes #3653

### Describe testing done for PR
- Verified that all the Context/Target related commands/features are enabled and user can use it without configuring any additional feature-flag manually

### Release note

```release-note
Enable Context/Target feature by default
```

### CODE REVIEW

**Review by marckhouzam — APPROVED** [review]
Works great.

LGTM

**Comment by mpanchajanya** [comment]
LGTM.

**Comment by alfredthenarwhal** [comment]
> @anujc25:  /test install-vc7
Commit: 7b807c6

Tests passed! Build no: 3441

**Review by mpanchajanya — APPROVED** [review]

**Review by chandrareddyp — APPROVED** [review]

**Review by prkalle — APPROVED** [review]
LGTM. Thanks!

**Comment by vuil** [comment]
nit: in your PR description: 
current logic does change the value
I think you mean does not change the value.

Still thinking if there is a better name for the flag. using -v2 when the original was never publicly exposed feels weird.

**Review by vuil — APPROVED** [review]
lgtm. holding till other PRs get in.

**Comment by vuil** [comment]
given the original flag was actually out, the alternative name, while not pretty, seems reasonable.

**Pull request merged**
