### PR TITLE
[WIP] Add version suffix v1.0.0 to Oracle Clusterclass

### PR DESCRIPTION
**Pull request by randomvariable**
### Which issue(s) this PR fixes
Ports #3908 to Oracle

### Describe testing done for PR

WIP

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @randomvariable:  /test install-vc7
Commit: 640ea9d

Build failed! Build no: 3532

**Comment by alfredthenarwhal** [comment]
> @randomvariable:  /test install-oracle
Commit: 640ea9d

Tests failed! Build no: 3533

**Review by imikushin — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
> @randomvariable:  /test install-oracle
Commit: 6b59795

Build failed! Build no: 3537

**Review by XudongLiuHarold — COMMENTED** [review]
We also need to add `OCI_CLUSTER_CLASS_VERSION` here:
https://github.com/vmware-tanzu/tanzu-framework/blob/main/providers/config_default.yaml#L770, otherwise the ytt will throw errors:
```
2022-12-11 07:08:41 gobuilds.Compile : 07:08:41.020 build      INFO         Error: couldn't generate imgpkg lock output file: couldn't run ytt command: ytt: Error:
2022-12-11 07:08:41 gobuilds.Compile : 07:08:41.020 build      INFO         - undefined: tkg
2022-12-11 07:08:41 gobuilds.Compile : 07:08:41.021 build      INFO             upstream/base.yaml:15 |       name: #@ tkg-oci-kcp.format(data.values.OCI_CLUSTER_CLASS_VERSION)
```

**Pull request closed without merging**
