### PR TITLE
set the node-ip correctly for kube-vip IPv6-only

### PR DESCRIPTION
**Pull request by adobley**
### What this PR does / why we need it
set the node-ip to a valid IPv6 address on the VM before kube-vip starts so that pods do not wind up with the kube-vip address

### Describe testing done for PR

Created a vSphere management cluster with kube-vip enabled and verified that the node-ip was set correctly.

### Release note

```release-note
N/A
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @christianang:  /test install-vc7
Commit: dcb6ba9

Tests failed! Build no: 3662

**Comment by alfredthenarwhal** [comment]
> @adobley:  /test install-vc7
Commit: dcb6ba9

Build failed! Build no: 3664

**Review by christianang — APPROVED** [review]

**Comment by adobley** [comment]
I don't know why the bot hasn't updated, but the tests are passing :)

**Review by rajathagasthya — APPROVED** [review]

**Pull request merged**
