### PR TITLE
Add antreaNSXPodRoutingEnabled field to the CPIConfig CR.

### PR DESCRIPTION
**Pull request by HanFa**
### What this PR does / why we need it

Add antreaNSXPodRoutingEnabled field to the CPIConfig CR. With this PR, the cluster admin is able to deploy VSphereCPIConfig CR like this to turn on the routable pod feature.

```
apiVersion: cpi.tanzu.vmware.com/v1alpha1
kind: VSphereCPIConfig
metadata:
  name: #@ "{}-routable".format(data.values.TKR_VERSION)
  namespace: #@ data.values.GLOBAL_NAMESPACE
spec:
  vsphereCPI:
    mode: vsphereParavirtualCPI
    antreaNSXPodRoutingEnabled: true
```

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note
Add antreaNSXPodRoutingEnabled field to the CPIConfig CR.
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

Addon controller integration test (running)

### CODE REVIEW

**Review by lubronzhan — APPROVED** [review]
/lgtm

**Comment by vijaykatam** [comment]
This config https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/providers/yttcb/clusterbootstrap.yaml#L48 needs an update as well. Is there a package update for this change as well?

**Comment by HanFa** [comment]
> This config https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/providers/yttcb/clusterbootstrap.yaml#L48 needs an update as well

this config file deploys a non-paravirt CPIConfig. However the new `antreaNSXPodRoutingEnabled` field is for paravirt mode only. So I think we don't need to update this file. Is there other place you are talking about?

**Comment by vijaykatam** [comment]
I see, then this change looks fine to me.

**Review by vijaykatam — APPROVED** [review]

**Pull request merged**
