### PR TITLE
Improve help for Makefile

### PR DESCRIPTION
**Pull request by mamachanko**
### What this PR does / why we need it

Improves content and appearance of `make [help]`.

The `awk` code for displaying help was already able to print section headers, but the section headers were not matched. Now, each section of Make target is preceeded by it's header when doing `make [help]`.

Not every Make target had a short doc string. And arguably, not every target needs one. Yet I added one to all of them.
Happy to walk this back.

Subtle colorization helps to tell things apart and draws attention to section headers first.

#### Before
before

#### After
after

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

Manual execution of `make`.

### Release note

```release-note
 * Better `make` help.
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by vuil** [comment]
Sorry, but some introductions to the Makefile means this needs a rebase and conflict resolution. There is also the odd behavior of the checks not kicking in, so let use the repush to check if that was a flake.

**Comment by mamachanko** [comment]
Just returned back to the office after a break. @vuil thanks for updating me on this. Rebased and pushed. 👌🏻

**Comment by vuil** [comment]
@mamachanko took the liberty to rebase the branch. I will merge if checks pass.

**Review by vuil — APPROVED** [review]
lgtm

**Pull request merged**
