### PR TITLE
Restarts containers in post kubeadm for capz

### PR DESCRIPTION
**Pull request by geetikabatra**
Restarts containers in post kubeadm so that /etc/host values are loaded.This is a hack for lack of Azure NLB hairpin support as it does not work for all hostNetwork pods

Signed-off-by: Geetika Batra geetikab@vmware.com

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by randomvariable** [comment]
need to run `packages/tkg-clusterclass/hack/sync-cc.sh` and ensure the clusterclass package is up to date as well.

**Comment by pridhi-arora** [comment]
> need to run `packages/tkg-clusterclass/hack/sync-cc.sh` and ensure the clusterclass package is up to date as well.

By running the above script, ` packages/tkg-clusterclass-docker/bundle/config/upstream/overlay-pod-security-admission.yaml ` got generated. Are we on right track?

**Comment by geetikabatra** [comment]
> need to run `packages/tkg-clusterclass/hack/sync-cc.sh` and ensure the clusterclass package is up to date as well.

@randomvariable  By running the above script. A new file got generated. p`ackages/tkg-clusterclass-docker/bundle/config/upstream/overlay-pod-security-admission.yaml`. Are we on right track.

**Comment by sonasingh46** [comment]
Closed in favour of https://github.com/vmware-tanzu/tanzu-framework/pull/4259

**Pull request closed without merging**
