### PR TITLE
Bump calico to 3.22.1

### LINKED ISSUE #2228: Bump calico to 3.22.1 for ClusterResourceSet
**Describe the feature request**
Bump calico to 3.22.1

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

### PR DESCRIPTION
**Pull request by 12345lcr**
### What this PR does / why we need it
* Bump calico to 3.22.1
* Sync input schemas from calico 3.22.1 packages
* Remove deprecated image fields from the calico addon secret
* Add skipCNIBinaries param to calico data values to skip cni binaries installation for vsphere, aws, and azure, since the cni binaries already exists in the base ova.
### Which issue(s) this PR fixes

Fixes https://github.com/vmware-tanzu/tanzu-framework/issues/2228, https://github.com/vmware-tanzu/tanzu-framework/issues/2263

### Release note

```release-note
Bump calico to 3.22.1
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by vijaykatam** [comment]
Change looks good.

**Comment by navidshaikh** [comment]
//usebom:sandbox/v1.6.0-zshippable/407060392850802626/tkg-compatibility

**Comment by navidshaikh** [comment]
> Tests canceled! Build no: 1961

ignore the failure, I've manually aborted the build, it needs usebom

**Review by anujc25 — APPROVED** [review]

**Pull request merged**
