### PR TITLE
Update BOM retrieval version to v0.25.2

### PR DESCRIPTION
**Pull request by sameerforge**
Signed-off-by: sameerkhan97 <sameerkh@vmware.com>

Part of Tanzu framework v0.25.2 release process.
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 3128

**Review by sriramandev — APPROVED** [review]
lgtm

**Comment by navidshaikh** [comment]
lets hold the PR for https://github.com/vmware-tanzu/tanzu-framework/pull/3660#issuecomment-1306757346

**Comment by vuil** [comment]
> #3660 (comment)

3660 should not be part of this release, I have closed it.

**Pull request merged**
