### PR TITLE
Correct go.mod for provider unit tests

### PR DESCRIPTION
**Pull request by randomvariable**
### What this PR does / why we need it

Package was being imported in two different ways, breaking IDEs. This standardises on intent.

Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

The repo was completely broken in VS code prior to this.

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note
NONE
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by randomvariable** [comment]
Why are we renaming this go module away from the  actual path to `github.com/vmware-tanzu/framework-unit` ? Is this going to be moved to a separate repo?

**Comment by jayunit100** [comment]
Hm pr looks fine if the tests still pass....

But I don't understand the question in your comment : I think *your PR* is renaming this path to framework-unit... is that the question your asking?

**Comment by randomvariable** [comment]
The go.mod was initially declared as 
`module github.com/vmware-tanzu/framework-unit`

This PR makes everything consistent with that. This is a rename. If it wasn't renamed, it should be

`module github.com/vmware-tanzu/tanzu-framework/pkg/v1/providers/tests/unit` 

unless there's an intention to move everything to `framework-unit` ?

**Comment by randomvariable** [comment]
Discussed with @jayunit100 about what we were trying to do and have fixed it up as appropriate.

**Comment by jayunit100** [comment]
`go test` works fine still so this is LGTM thanks naadir for keepin our dev-ux on track :)

**Review by jayunit100 — APPROVED** [review]

**Review by vuil — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
