### PR TITLE
Remove AVI_CONTROLLER_VERSION variable

### PR DESCRIPTION
**Pull request by chenlin07**
Signed-off-by: Chen Lin <linch@vmware.com>
### Which issue(s) this PR fixes

Remove AVI_CONTROLLER_VERSION variable
- We don't need this config variable anymore, since the avi_controller_version can be auto-detected.

Fixes #

### Release note

```release-note
Remove AVI_CONTROLLER_VERSION variable
```

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
> @chenlin07:  /test install-vc7
Commit: f73dfad

Build failed! Build no: 3336

**Comment by randomvariable** [comment]
Code coverage artificially went down even though code was being deleted. Should be safe to voerride.

**Review by XudongLiuHarold — APPROVED** [review]
LGTM

**Review by wjun — APPROVED** [review]
LGTM

**Pull request merged**
