### PR TITLE
Bump CAPI with rebased contents

### PR DESCRIPTION
**Pull request by jeffwubj**
### Which issue(s) this PR fixes

Fixes #
Bump Cluster API and providers, forked from https://github.com/vmware-tanzu/tanzu-framework/pull/3699 with pipeline fix

### Describe testing done for PR

- upstream pipelines all passed
- downstream install-azure, install-vc, multi-version vc passed
- install-aws failed as expected, pipeline needs a re-work to align with new CAPA behaviour

### Release note

```release-note

```

### CODE REVIEW

**Comment by jeffwubj** [comment]
//usebom:sandbox/v1.7.0-zshippable/431703182511446831/tkg-compatibility:v12

**Review by wjun — APPROVED** [review]
LGTM!

**Comment by vuil** [comment]
@jeffwubj please follow the PR template and provide some details on what the change is about, what tests were run, etc. 
Not sure if it is just temporary, but looks like this change broke some workflows on main.

**Comment by jeffwubj** [comment]
> @jeffwubj please follow the PR template and provide some details on what the change is about, what tests were run, etc. Not sure if it is just temporary, but looks like this change broke some workflows on main.

description updated.
this is not temporary but the CAP* bump PR, I have re-run all tests on https://github.com/vmware-tanzu/tanzu-framework/pull/3604 to see the latest status, feel free to let me know if anything has already been found

**Pull request merged**
