### PR TITLE
bump capi and providers with provider folder manually rebased

### PR DESCRIPTION
**Pull request by jeffwubj**
### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by jeffwubj** [comment]
//usebom:sandbox/v1.7.0-zshippable/431380820989605231/tkg-compatibility:v12

**Comment by marckhouzam** [comment]
This needs a rebase

**Comment by imikushin** [comment]
Pushed a commit resolving conflicts with main.

**Review by imikushin — APPROVED** [review]
LGTM

**Pull request closed without merging**
