### PR TITLE
Update vendir of cpi CRD to include the change of antreaNSXPodRouting…

### PR DESCRIPTION
**Pull request by lubronzhan**
…Enabled

### What this PR does / why we need it
Run vendir sync to add AntreaNSXPodRoutingEnabled definition in CPI CRD
In last PR https://github.com/vmware-tanzu/tanzu-framework/pull/2754, this CRD change was missed

### Which issue(s) this PR fixes

Fixes #https://github.com/vmware-tanzu/tanzu-framework/issues/2930

### Release note

```release-note
package-based-lcm: Add AntreaNSXPodRoutingEnabled to CPI CRD for uTKG routablePod
```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by HanFa — APPROVED** [review]
LGTM

**Comment by alfredthenarwhal** [comment]
Tests failed! Build no: 2375

**Review by vijaykatam — APPROVED** [review]
Change LGTM. Fill out PR template before merging.

**Pull request merged**
