### PR TITLE
Remove omitEmpty from boolean values to ensure all the bool values get displayed regardless of true or false

### LINKED ISSUE #2663: Antrea secret shows only data values which are true, false data values are not displayed
**Bug description**
Antrea secret shows only data values which are true, false data values are not displayed
```
➜  tanzu-framework git:(package-based-lcm) ✗ kubectl get secret mc-jun10-cluster-antrea-data-values -n tkg-system -o jsonpath='{.data.values\.yaml}' | base64 -d
infraProvider: aws
antrea:
    config:
        serviceCIDR: 100.64.0.0/13
        trafficEncapMode: encap
        tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
        featureGates:
            AntreaProxy: true
            EndpointSlice: true
            AntreaPolicy: true
            AntreaTraceflow: true
```            

**Affected product area (please put an X in all that apply)**

- [x] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Behaviour shud be to display both true and false data values

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

### PR DESCRIPTION
**Pull request by shivaani0505**
### What this PR does / why we need it
Remove omitEmpty from boolean values to ensure all the bool values get displayed regardless of true or false

### Which issue(s) this PR fixes

Fixes #2663 

### Release note

```release-note
package-based-lcm: fix issue for Marshal function from yaml module which treats false booleans as if they were nil values, and thus omits them from the resulted json for data values secret
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by vijaykatam** [comment]
Add release note and reasoning on why we are removing `omitEmpty` would be good since convention is `omitEmpty`. We should also followup with a CRD sync in the package.

**Comment by shivaani0505** [comment]
> Add release note and reasoning on why we are removing `omitEmpty` would be good since convention is `omitEmpty`. We should also followup with a CRD sync in the package.

@vijaykatam , added Release notes.
Reasoning: fix issue for Marshal function from yaml module which treats false booleans as if they were nil values, and thus omits them from the resulted json for data values secret

Do you also want me to update types file. If yes, then I will regenerate the CRDs

**Comment by knabben** [comment]
would be nice to have some unit tests for these marshalling functions

**Review by vijaykatam — COMMENTED** [review]
Change looks good. As discussed earlier today, check if we need to be consistent for  serializations in calico and other addons. If not, please fix them here or log issue(s).

**Review by vijaykatam — APPROVED** [review]

**Pull request merged**
