### PR TITLE
Fix YAML marshaling error introduced by #2524

### PR DESCRIPTION
**Pull request by imikushin**
### What this PR does / why we need it

Without this fix, `bom-metadata` ConfigMap in the `tkr-system` namespace would differ in `binaryData.compatibility` value from its contents prior to #2524.

Adding a unit test that would fail illustrating the difference:
```
  Expected
      <string>: "Manage..."
  to equal       |
      <string>: "manage..."
```

### Which issue(s) this PR fixes

N/A

### Describe testing done for PR

Add the above mentioned unit test.
Manually run the legacy TKR controller to make sure bon-metadata content is correct.

### Release note

```release-note
NONE
```

### PR Checklist

- [X] Squash the commits into one or a small number of logical commits
      
- [X] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [X] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by vuil** [comment]
remove hold once install-vc7 passes

**Review by vuil — APPROVED** [review]
lgtm, thanks for the fix.

**Review by prkalle — APPROVED** [review]
LGTM. Thanks

**Comment by alfredthenarwhal** [comment]
> @vuil:  /test install-vc7
Commit: ff9e211

Tests failed! Build no: 2124

**Comment by navidshaikh** [comment]
/test install-vc7

build failure, retrying..

**Comment by alfredthenarwhal** [comment]
> @navidshaikh:  /test install-vc7
Commit: ff9e211

Tests failed! Build no: 2125

**Comment by vuil** [comment]
test failure looks unrelated to this change, and this fix is absolutely needed, so merging first and continue to triage.

**Comment by alfredthenarwhal** [comment]
> @vuil:  /test install-vc7
Commit: ff9e211

Tests failed! Build no: 2128

**Pull request merged**
