### PR TITLE
Change AKO default service type to npl when cni is antrea

### LINKED ISSUE #2939: Set default AKO service type to NodePortLocal when CNI is antrea
(This is used to request new product features)

**Describe the feature request**

- The default AKO service type should be set to `NodePortLocal` when the cluster CNI is antrea, since `NodePortLocal` routing mode allows NSX ALB's Service Engine directly reaches out to the pod and provides better performance.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [x] User Experience

**Additional context**

- This feature that needs antrea is the cluster's CNI implementation.

### PR DESCRIPTION
**Pull request by XudongLiuHarold**
Signed-off-by: Xudong Liu <xudongl@vmware.com>

### What this PR does / why we need it

- Change AKO(vmware/load-balancer-and-ingress-service)'s default service type to `NodePortLocal` when cluster CNI is antrea.
- Pass `nodeNetworkList` to ako configmap since it becomes a required value when service type is not `NodePort`

### Which issue(s) this PR fixes

Fixes #2939

### Describe testing done for PR

Created vSphere management cluster & workload clusters verified the change.

### Release note

```release-note
When cluster's CNI implementation is Antrea, AKO will use NodePortLocal routing mode by default
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by alfredthenarwhal** [comment]
Tests failed! Build no: 2380

**Review by HanFa — APPROVED** [review]
lgtm, although ideally we need unit test to cover these

**Review by sbhatp — APPROVED** [review]
LGTM

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2401

**Comment by alfredthenarwhal** [comment]
Tests failed! Build no: 2402

**Pull request merged**
