### PR TITLE
Update CPI dependency to 1.24.0

### PR DESCRIPTION
**Pull request by lubronzhan**
### What this PR does / why we need it
As title
### Which issue(s) this PR fixes

Fixes #https://github.com/vmware-tanzu/tanzu-framework/issues/3233

### Release note

```release-note
Bump CPI to 1.24.0
```

### CODE REVIEW

**Review by randomvariable — APPROVED** [review]

**Review by vuil — APPROVED** [review]
lgtm, thanks for following up on the tests.

**Pull request merged**
