### PR TITLE
Remove uri format specification from clusterclass definition

### PR DESCRIPTION
**Pull request by saji-pivotal**
### What this PR does / why we need it
Removes the uri format specification.
This is preventing us from creating a cluster when use a customImageRepository

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
1. I had the following section in my cluster.yaml, and ran a kube apply
```
- name: imageRepository
      value:
        host: projects-stg.registry.vmware.com

kubectl apply -f ~/tmp-aws-cluster.yaml 
The Cluster "test-tmp-aws-2" is invalid: spec.topology.variables[1].host: Invalid value: "projects-stg.registry.vmware.com/tkg": host in body must be of type uri: "projects-stg.registry.vmware.com/tkg"
```

2. I then prepended the host field with `http://`

```
- name: imageRepository
      value:
        host: http://projects-stg.registry.vmware.com

kubectl apply -f ~/tmp-aws-cluster.yaml 
cluster.cluster.x-k8s.io/test-tmp-aws-2 created
```

This means that the uri format requires a `http://` or `https://` at the beginning.

Unfortunately, we cannot specify the protocol in the beginning of the url because we do a `docker pull <IMAGE_REPO>` while creating the cluster. The only viable solution is to loosen the format restriction

### Release note

```release-note

```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Review by tenczar — CHANGES_REQUESTED** [review]
We will definitely want this in pkg/v1/providers/infrastructure-aws/1.2.0/cconly/base.yml and it would be nice to make the same change in infrastructure-azure and infrastructure-vsphere

**Comment by saji-pivotal** [comment]
@tenczar I've made the change in `providers/infrastructure-aws/1.2.0` . This format is not specified in azure and vsphere

**Review by tenczar — APPROVED** [review]
LGTM

**Comment by vuil** [comment]
lgtm.

P.S. The PR description formatting is kinda messed up.

**Review by anujc25 — APPROVED** [review]
LGTM

**Pull request merged**
