### PR TITLE
revert version bump, which cause downstream pipeline failure

### PR DESCRIPTION
**Pull request by jeffwubj**
### Which issue(s) this PR fixes
Previously, 1.21 support is removed, which cause all downstream multi-version pipelines failed, after discussion with downstream team, an agreement is made to add 1.21 back to support list. bolt team will info tanzu-framework when 1.24 is ready.

Fixes #

### Release note

```release-note

```

### CODE REVIEW

**Comment by sathyanarays** [comment]
Please provide some details in the PR description. Fill the applicable among the following sections:
- What this PR does / why we need it
- Describe testing done for PR

**Review by wjun — APPROVED** [review]

**Comment by alfredthenarwhal** [comment]
Build failed! Build no: 2945

**Review by tenczar — APPROVED** [review]
LGTM

**Comment by ramineni** [comment]
@jeffwubj This should be reverted back again now? still shows 1.21 supported , https://github.com/vmware-tanzu/tanzu-framework/blob/main/tkg/tkgconfighelper/validate.go#L26

**Pull request merged**
