### PR TITLE
Plumb legacy skipCNIBinaries config to CalicoConfig API

### LINKED ISSUE #2370: Plumb Calico CLI addon configs to CalicoConfig API
CLI has legacy addon configs like ANTREA_TRAFFIC_ENCAP_MODE that is used to create an addon secret. In new Addons APIs since we are using ClusterBootStrap and AddonConfig API we need to plumb the legacy addon configs to new APIs.

Create ClusterBootstrap and AddonConfig API overalys.

### PR DESCRIPTION
**Pull request by 12345lcr**
### What this PR does / why we need it
Plumb legacy skipCNIBinaries config to CalicoConfig API
https://github.com/vmware-tanzu/tanzu-framework/blob/50594bfb0271126c92e3b52a82b4a5f52de3f405/pkg/v1/providers/ytt/02_addons/cni/calico/calico_addon_data.lib.yaml#L11-L12

### Which issue(s) this PR fixes

Fixes: https://github.com/vmware-tanzu/tanzu-framework/issues/2370, https://github.com/vmware-tanzu/tanzu-framework/issues/2415

### Release note

```release-note
Plumb legacy skipCNIBinaries config to CalicoConfig API
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### CODE REVIEW

**Comment by shyaamsn** [comment]
LGTM. @vmware-tanzu/tanzu-framework-reviewers Could you please review/approve this PR. It has been pending for a long time.

**Comment by vijaykatam** [comment]
Change looks good. Do we need to backport to release-0.25/Fuji release?

**Comment by vijaykatam** [comment]
Could you also add release note prior to merging?

**Review by vijaykatam — APPROVED** [review]

**Comment by 12345lcr** [comment]
Thanks @vijaykatam , release note updated. The downstream JIRA indicate that this fix is part of G release.

**Pull request merged**
