### PR TITLE
Change audit policy api version to audit.k8s.io/v1 to adopt 1.24

### PR DESCRIPTION
**Pull request by jeffwubj**
### Which issue(s) this PR fixes

ENABLE_AUDIT_LOGGING not work with tkr 1.24, kcp provision will hang, this impacts tkgm on vsphere, tkgm on aws and tkgm on azure.

audit-policy.yaml provided by tkg mismatched with k8s 1.24, api server in control plane is failing on reading /etc/kubernetes/audit-policy.yaml with version audit.k8s.io/v1beta1.

the upstream [commit](https://github.com/kubernetes/kubernetes/commit/fcc282f9f2050aaa4007d6f0444b0f4972925fea#diff-912b70d5dfa34427faa8ddbc816971ad8282791620efd1f0d7eeee548b8ab7a2) has disabled v1[alpha|beta]1 in api server for 1.24

In this PR, change audit policy api version to v1

### Describe testing done for PR

- set ENABLE_AUDIT_LOGGING to true, could spin up aws mc with tkr 1.24.x
- set ENABLE_AUDIT_LOGGING to true, could spin up azure mc with tkr 1.24.x
- multi version vsphere installation passed

### Release note

```release-note

```

### CODE REVIEW

**Comment by imikushin** [comment]
Hey @jeffwubj , it seems we have a bunch more places where `audit.k8s.io/v1beta1` is used than you've fixed.

**Comment by jeffwubj** [comment]
> Hey @jeffwubj , it seems we have a bunch more places where `audit.k8s.io/v1beta1` is used than you've fixed.

oh, would you mind helping to share where are them ... just researched, not sure what is missed

**Comment by imikushin** [comment]
> > Hey @jeffwubj , it seems we have a bunch more places where `audit.k8s.io/v1beta1` is used than you've fixed.
> 
> oh, would you mind helping to share where are them ... just researched, not sure what is missed

Sorry, my bad. Performed a full text search over my local workspace and got matches in 38 files. After your comment did a search on a fresh checkout: got exactly the 7 matches you've fixed!

**Review by imikushin — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
