### PR TITLE
provider: Introduce Pod Security Standard for non-CC and CC based Clusters

### PR DESCRIPTION
**Pull request by chrischdi**
Note: I will be on PTO from 20th November until 4th of December). @ramineni will takeover during that time!

### What this PR does / why we need it

Introduces:

* Namespace labels for CAPZ and CAPD provider to specify privileged pod security admission
* Overlay for ClusterClasses to enable and configure Pod Security Standard for v1.24 clusters
* Overlay for non-ClusterClass clusters to enable and configure Pod Security Standard for v1.24 clusters
* Migration code for non-ClusterClass clusters to enable Pod Security Standard when upgrading to v1.24
* Fixes the audit-log patches for ClusterClass to work via the `kcp-empty-array-overlay.yaml`

A follow-up PR will raises the enablement to v1.24, as soon as v1.24 is available here.

### Which issue(s) this PR fixes

Replaces #3693

Fixes #

### Describe testing done for PR

- Validated in manual CAPA installation (ClusterClass + non ClusterClass)
- vcenter pipelines succeeded
- Tested overlays on local capd (with and without clusterclass)
- Tested overlays using TKG + small changes which enable PSA already for v1.23

### Release note

```release-note
Enable pod security admission per default for Clusters in audit and warn mode. Also introduces variables to the ClusterClasses to make it configurable for ClusterClass based clusters.
```

### CODE REVIEW

**Comment by chrischdi** [comment]
//usebom:sandbox/v1.7.0-zshippable/433635283682987431/tkg-compatibility:v12

**Comment by chrischdi** [comment]
@tenczar : could you maybe give this another look?

**Comment by chrischdi** [comment]
//usebom:sandbox/v1.7.0-zshippable/434527166659564004/tkg-compatibility:v12

**Comment by chrischdi** [comment]
//usebom:sandbox/v1.7.0-zshippable/434686738921714988/tkg-compatibility:v12

**Review by tenczar — APPROVED** [review]
LGTM

**Comment by chrischdi** [comment]
rebased due to merge conflict.

**Comment by chrischdi** [comment]
Again rebase

**Comment by chrischdi** [comment]
Note: I will be on PTO from 20th November until 4th of December). @ramineni will takeover during that time!

**Comment by ramineni** [comment]
@tenczar could you review this again. 
rebased on latest main. No other changes made after last LGTM. Thanks

**Comment by alfredthenarwhal** [comment]
> @ramineni:  /test all
Commit: a12b59e

Tests failed! Build no: 3348

**Comment by ramineni** [comment]
CAPZ, CAPA, CAPD failures doesnt seem to be relevant to this PR.

**Comment by randomvariable** [comment]
Do not merge before #3846

**Review by randomvariable — APPROVED** [review]

**Pull request merged**
